<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('psbison')->create('invoicedetail', function (Blueprint $table) {
            $table->integer('ivh_hdrnumber')->nullable();
            $table->integer('ivd_number');
            $table->integer('stp_number')->nullable();
            $table->string('ivd_description', 60)->nullable();
            $table->string('cht_itemcode', 6)->nullable();
            $table->float('ivd_quantity', 53, 0)->nullable();
            $table->decimal('ivd_rate', 19, 4)->nullable();
            $table->decimal('ivd_charge', 19, 4)->nullable();
            $table->string('ivd_taxable1', 1)->nullable();
            $table->string('ivd_taxable2', 1)->nullable();
            $table->string('ivd_taxable3', 1)->nullable();
            $table->string('ivd_taxable4', 1)->nullable();
            $table->string('ivd_unit', 6)->nullable();
            $table->string('cur_code', 6)->nullable();
            $table->dateTime('ivd_currencydate')->nullable();
            $table->string('ivd_glnum', 32)->nullable();
            $table->integer('ord_hdrnumber')->nullable();
            $table->string('ivd_type', 6)->nullable();
            $table->string('ivd_rateunit', 6)->nullable();
            $table->string('ivd_billto', 8)->nullable();
            $table->float('ivd_itemquantity', 53, 0)->nullable();
            $table->integer('ivd_subtotalptr')->nullable();
            $table->decimal('ivd_allocatedrev', 19, 4)->nullable();
            $table->integer('ivd_sequence')->nullable();
            $table->string('ivd_invoicestatus', 6)->nullable();
            $table->integer('mfh_hdrnumber')->nullable();
            $table->string('ivd_refnum', 30)->nullable();
            $table->string('cmd_code', 8)->nullable();
            $table->string('cmp_id', 8)->nullable();
            $table->float('ivd_distance', 53, 0)->nullable();
            $table->string('ivd_distunit', 6)->nullable();
            $table->float('ivd_wgt', 53, 0)->nullable();
            $table->string('ivd_wgtunit', 6)->nullable();
            $table->decimal('ivd_count', 10)->nullable();
            $table->string('ivd_countunit', 6)->nullable();
            $table->integer('evt_number')->nullable();
            $table->string('ivd_reftype', 6)->nullable();
            $table->float('ivd_volume', 53, 0)->nullable();
            $table->string('ivd_volunit', 6)->nullable();
            $table->string('ivd_orig_cmpid', 8)->nullable();
            $table->binary('timestamp')->nullable();
            $table->decimal('ivd_payrevenue', 19, 4)->nullable();
            $table->smallInteger('ivd_sign')->nullable();
            $table->decimal('ivd_length', 19, 4)->nullable();
            $table->string('ivd_lengthunit', 6)->nullable();
            $table->decimal('ivd_width', 19, 4)->nullable();
            $table->string('ivd_widthunit', 6)->nullable();
            $table->decimal('ivd_height', 19, 4)->nullable();
            $table->string('ivd_heightunit', 6)->nullable();
            $table->string('ivd_exportstatus', 6)->nullable();
            $table->string('cht_basisunit', 6)->nullable();
            $table->string('ivd_remark')->nullable();
            $table->integer('tar_number')->nullable();
            $table->string('tar_tariffnumber', 12)->nullable();
            $table->string('tar_tariffitem', 12)->nullable();
            $table->string('ivd_fromord', 1)->nullable();
            $table->string('ivd_zipcode', 10)->nullable();
            $table->smallInteger('ivd_quantity_type')->nullable();
            $table->string('cht_class', 6)->nullable();
            $table->string('ivd_mileagetable', 4)->nullable();
            $table->smallInteger('ivd_charge_type')->nullable();
            $table->string('ivd_trl_rent', 13)->nullable();
            $table->dateTime('ivd_trl_rent_start')->nullable();
            $table->dateTime('ivd_trl_rent_end')->nullable();
            $table->smallInteger('ivd_rate_type')->nullable();
            $table->string('last_updateby', 256)->nullable();
            $table->dateTime('last_updatedate')->nullable();
            $table->string('ivd_revtype1', 6)->nullable();
            $table->string('cht_lh_min', 1)->nullable();
            $table->string('cht_lh_rev', 1)->nullable();
            $table->string('cht_lh_stl', 1)->nullable();
            $table->string('cht_lh_rpt', 1)->nullable();
            $table->integer('cht_rollintolh')->nullable();
            $table->string('cht_lh_prn', 1)->nullable();
            $table->integer('fgt_number')->nullable();
            $table->integer('ivd_paylgh_number')->nullable();
            $table->string('ivd_tariff_type', 1)->nullable();
            $table->string('ivd_taxid', 15)->nullable();
            $table->decimal('ivd_ordered_volume', 18, 0)->nullable();
            $table->decimal('ivd_ordered_loadingmeters', 18, 0)->nullable();
            $table->decimal('ivd_ordered_count', 18, 0)->nullable();
            $table->decimal('ivd_ordered_weight', 18, 0)->nullable();
            $table->decimal('ivd_loadingmeters', 18, 0)->nullable();
            $table->string('ivd_loadingmeters_unit', 6)->nullable();
            $table->string('ivd_hide', 1)->nullable();
            $table->decimal('ivd_baserate', 19, 4)->nullable();
            $table->decimal('ivd_rawcharge', 19, 4)->nullable();
            $table->decimal('ivd_oradjustment', 19, 4)->nullable();
            $table->decimal('ivd_cbadjustment', 19, 4)->nullable();
            $table->decimal('ivd_fsc', 19, 4)->nullable();
            $table->string('ivd_splitbillratetype', 10)->nullable();
            $table->integer('ivd_bolid')->nullable();
            $table->decimal('ivd_shared_wgt', 19, 4)->nullable();
            $table->string('ivd_ARTaxAuth', 6)->nullable();
            $table->decimal('ivd_tollcost', 19, 4)->nullable();
            $table->decimal('ivd_miscmoney1', 19, 4)->nullable();
            $table->string('ivd_billable_flag', 1)->nullable();
            $table->string('ivd_post_invoice', 1)->nullable();
            $table->string('ivd_paid_indicator', 1)->nullable();
            $table->decimal('ivd_paid_amount', 19, 4)->nullable();
            $table->float('ivd_actual_quantity', 53, 0)->nullable();
            $table->string('ivd_actual_unit', 6)->nullable();
            $table->decimal('ivd_tax_basis', 19, 4)->nullable();
            $table->float('ivd_loaded_distance', 53, 0)->nullable();
            $table->float('ivd_empty_distance', 53, 0)->nullable();
            $table->string('fgt_supplier', 8)->nullable();
            $table->string('ivd_showas_cmpid', 8)->nullable();
            $table->integer('ivd_leaseassetid')->nullable();
            $table->string('ivd_MaskFromRating', 1)->nullable();
            $table->integer('ivd_car_key')->nullable();
            $table->string('ivd_ord_number', 13)->nullable();
            $table->float('ivd_allocated_quantity', 53, 0)->nullable();
            $table->decimal('ivd_allocated_rate', 19, 4)->nullable();
            $table->decimal('ivd_allocated_charge', 19, 4)->nullable();
            $table->integer('ivd_allocated_ivd_number')->nullable();
            $table->integer('dbsd_id_tariff')->nullable();
            $table->string('ivd_allocation_type', 6)->nullable();
            $table->float('ivd_allocated_qty', 53, 0)->nullable();
            $table->integer('ivd_reconcile_tariff')->nullable();
            $table->string('ivd_comment')->nullable();
            $table->dateTime('ivd_transdate')->nullable();
            $table->string('ivd_branch', 12)->nullable();
            $table->string('ivd_delays', 6)->nullable();
            $table->string('dw_timestamp');
            $table->float('ivd_rate_factor', 53, 0)->nullable();
            $table->integer('ivd_ico_pyd_number_parent')->nullable();
            $table->string('ivd_description_type', 1)->nullable();
            $table->float('ivd_rated_qty', 53, 0)->nullable();
            $table->decimal('ivd_rated_rate', 19, 4)->nullable();
            $table->integer('dbst_rollinto_tar')->nullable();
            $table->string('ivd_customer_char1', 1)->nullable();
            $table->dateTime('ivd_billdate')->nullable();
            $table->float('ivd_pallets', 53, 0)->nullable();
            $table->string('ivd_palletunits', 6)->nullable();
            $table->string('cmd_NMFC_class', 8)->nullable();
            $table->string('cmd_NMFC_rate_class', 8)->nullable();
            $table->integer('deficit_row')->nullable();
            $table->decimal('ivd_rate_per', 10)->nullable();
            $table->decimal('ivd_sub_charge', 10)->nullable();
            $table->decimal('ivd_discount_rate', 10)->nullable();
            $table->decimal('ivd_discount', 10)->nullable();
            $table->integer('disc_tar_number')->nullable();
            $table->decimal('ivd_discount_qty', 10)->nullable();
            $table->decimal('ivd_discount_per', 10)->nullable();
            $table->string('ivd_definition', 6)->nullable();
            $table->dateTime('INS_TIMESTAMP');
        });
    }

    public function down(): void
    {
        Schema::connection('psbison')->dropIfExists('invoicedetail');
    }
};
