<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('psbison')->create('company', function (Blueprint $table) {
            $table->string('cmp_id', 8);
            $table->string('cmp_name', 100)->nullable();
            $table->string('cmp_address1', 100)->nullable();
            $table->string('cmp_address2', 100)->nullable();
            $table->integer('cmp_city')->nullable();
            $table->string('cmp_zip', 10)->nullable();
            $table->string('cmp_primaryphone', 20)->nullable();
            $table->string('cmp_secondaryphone', 20)->nullable();
            $table->string('cmp_faxphone', 20)->nullable();
            $table->string('cmp_shipper', 1)->nullable();
            $table->string('cmp_consingee', 1)->nullable();
            $table->string('cmp_billto', 1)->nullable();
            $table->string('cmp_othertype1', 6)->nullable();
            $table->string('cmp_othertype2', 6)->nullable();
            $table->string('cmp_artype', 6)->nullable();
            $table->string('cmp_invoicetype', 6)->nullable();
            $table->string('cmp_revtype1', 6)->nullable();
            $table->string('cmp_revtype2', 6)->nullable();
            $table->string('cmp_revtype3', 6)->nullable();
            $table->string('cmp_revtype4', 6)->nullable();
            $table->string('cmp_currency', 6)->nullable();
            $table->string('cmp_active', 1)->nullable();
            $table->integer('cmp_opens_mo')->nullable();
            $table->integer('cmp_closes_mo')->nullable();
            $table->decimal('cmp_creditlimit', 19, 4)->nullable();
            $table->decimal('cmp_creditavail', 19, 4)->nullable();
            $table->string('cmp_mileagetable', 4)->nullable();
            $table->string('cmp_mastercompany', 8)->nullable();
            $table->string('cmp_terms', 3)->nullable();
            $table->string('cmp_defaultbillto', 8)->nullable();
            $table->integer('cmp_edi214')->nullable();
            $table->integer('cmp_edi210')->nullable();
            $table->integer('cmp_edi204')->nullable();
            $table->string('cmp_state', 6)->nullable();
            $table->string('cmp_region1', 6)->nullable();
            $table->string('cmp_region2', 6)->nullable();
            $table->string('cmp_region3', 6)->nullable();
            $table->string('cmp_region4', 6)->nullable();
            $table->string('cmp_addnewshipper', 1)->nullable();
            $table->string('cmp_opensun', 1)->nullable();
            $table->string('cmp_openmon', 1)->nullable();
            $table->string('cmp_opentue', 1)->nullable();
            $table->string('cmp_openwed', 1)->nullable();
            $table->string('cmp_openthu', 1)->nullable();
            $table->string('cmp_openfri', 1)->nullable();
            $table->string('cmp_opensat', 1)->nullable();
            $table->string('cmp_payfrom', 8)->nullable();
            $table->string('cmp_mapfile', 8)->nullable();
            $table->string('cmp_contact', 40)->nullable();
            $table->text('cmp_directions')->nullable();
            $table->string('timestamp')->nullable();
            $table->string('cty_nmstct', 25)->nullable();
            $table->string('cmp_misc1', 254)->nullable();
            $table->string('cmp_misc2', 254)->nullable();
            $table->string('cmp_misc3', 254)->nullable();
            $table->string('cmp_misc4', 254)->nullable();
            $table->smallInteger('cmp_mbdays')->nullable();
            $table->dateTime('cmp_lastmb')->nullable();
            $table->smallInteger('cmp_invcopies')->nullable();
            $table->string('cmp_transfertype', 6)->nullable();
            $table->string('cmp_altid', 25)->nullable();
            $table->string('cmp_updatedby', 20)->nullable();
            $table->dateTime('cmp_updateddate')->nullable();
            $table->string('cmp_defaultpriority', 6)->nullable();
            $table->string('cmp_invoiceto', 3)->nullable();
            $table->integer('cmp_invformat')->nullable();
            $table->string('cmp_invprintto', 1)->nullable();
            $table->dateTime('cmp_creditavail_update')->nullable();
            $table->string('cmd_code', 8)->nullable();
            $table->dateTime('junknotinuse')->nullable();
            $table->string('cmp_agedinvflag', 1)->nullable();
            $table->integer('cmp_max_dunnage')->nullable();
            $table->decimal('cmp_acc_balance', 19, 4)->nullable();
            $table->dateTime('cmp_acc_dt')->nullable();
            $table->integer('cmp_opens_tu')->nullable();
            $table->integer('cmp_closes_tu')->nullable();
            $table->integer('cmp_opens_we')->nullable();
            $table->integer('cmp_closes_we')->nullable();
            $table->integer('cmp_opens_th')->nullable();
            $table->integer('cmp_closes_th')->nullable();
            $table->integer('cmp_opens_fr')->nullable();
            $table->integer('cmp_closes_fr')->nullable();
            $table->integer('cmp_opens_sa')->nullable();
            $table->integer('cmp_closes_sa')->nullable();
            $table->integer('cmp_opens_su')->nullable();
            $table->integer('cmp_closes_su')->nullable();
            $table->string('cmp_subcompany', 6)->nullable();
            $table->dateTime('cmp_createdate')->nullable();
            $table->string('cmp_taxtable1', 1)->nullable();
            $table->string('cmp_taxtable2', 1)->nullable();
            $table->string('cmp_taxtable3', 1)->nullable();
            $table->string('cmp_taxtable4', 1)->nullable();
            $table->string('cmp_quickentry', 1)->nullable();
            $table->integer('cmp_slack_time')->nullable();
            $table->string('cmp_mailto_name', 30)->nullable();
            $table->string('cmp_mailto_address1', 40)->nullable();
            $table->string('cmp_mailto_address2', 40)->nullable();
            $table->integer('cmp_mailto_city')->nullable();
            $table->string('cmp_mailto_state', 6)->nullable();
            $table->string('cmp_mailto_zip', 10)->nullable();
            $table->string('mailto_cty_nmstct', 25)->nullable();
            $table->string('cmp_mailto_crterm1', 6)->nullable();
            $table->string('cmp_mailto_crterm2', 6)->nullable();
            $table->string('cmp_mailto_crterm3', 6)->nullable();
            $table->decimal('cmp_latseconds', 11, 3)->nullable();
            $table->decimal('cmp_longseconds', 11, 3)->nullable();
            $table->string('cmp_mbformat', 20)->nullable();
            $table->string('cmp_mbgroup', 20)->nullable();
            $table->integer('cmp_centroidcity')->nullable();
            $table->string('cmp_centroidctynmstct', 25)->nullable();
            $table->string('cmp_centroidzip', 10)->nullable();
            $table->float('cmp_ooa_mileage', 53, 0)->nullable();
            $table->float('cmp_ooa_mileage_stops', 53, 0)->nullable();
            $table->string('cmp_mapaddress', 50)->nullable();
            $table->string('cmp_primaryphoneext', 6)->nullable();
            $table->string('cmp_secondaryphoneext', 6)->nullable();
            $table->string('cmp_usestreetaddr', 1)->nullable();
            $table->integer('cmp_palletcount')->nullable();
            $table->string('cmp_fueltableid', 8)->nullable();
            $table->string('cmp_podcontact', 50)->nullable();
            $table->string('cmp_podphone', 20)->nullable();
            $table->integer('grp_id')->nullable();
            $table->string('cmp_parent', 1)->nullable();
            $table->string('cmp_country', 50)->nullable();
            $table->string('cmp_address3', 100)->nullable();
            $table->integer('cmp_slacktime_late')->nullable();
            $table->string('cmp_geoloc', 50)->nullable();
            $table->string('cmp_geoloc_forsearch', 50)->nullable();
            $table->decimal('cmp_min_charge', 19, 4)->nullable();
            $table->string('cmp_service_location', 1)->nullable();
            $table->string('cmp_psoverride', 1)->nullable();
            $table->string('bisoninv_email')->nullable();
            $table->integer('bisoninv_faxconf')->nullable();
            $table->integer('bisoninv_customsdoc')->nullable();
            $table->string('bisoninv_edibillto', 8)->nullable();
            $table->string('cmp_image_routing1', 254)->nullable();
            $table->string('cmp_image_routing2', 254)->nullable();
            $table->string('cmp_image_routing3', 254)->nullable();
            $table->string('cmp_mailtoTermsMatchFlag', 1)->nullable();
            $table->string('cmp_MailtToForLinehaulFlag', 1)->nullable();
            $table->decimal('cmp_max_weight', 19, 4)->nullable();
            $table->string('cmp_max_weightunits', 6)->nullable();
            $table->string('cmp_ivformat', 20)->nullable();
            $table->string('cmp_ivgroup', 20)->nullable();
            $table->string('cmp_addcurrencysurcharge', 1)->nullable();
            $table->string('cmp_port', 1);
            $table->decimal('cmp_currencysurchargebase', 19, 4)->nullable();
            $table->string('cmp_taxid', 15)->nullable();
            $table->string('cmp_gp_class', 11)->nullable();
            $table->string('doc_language', 30);
            $table->string('cmp_depot', 1);
            $table->string('ltsl_auto_add_pul_flag', 1)->nullable();
            $table->string('ltsl_default_pickup_event', 6)->nullable();
            $table->string('ltsl_default_delivery_event', 6)->nullable();
            $table->integer('cmp_PUPTimeAllowance')->nullable();
            $table->integer('cmp_DRPTimeAllowance')->nullable();
            $table->integer('bison_latlongtype')->nullable();
            $table->string('bison_timezone', 3)->nullable();
            $table->integer('cmp_latlongverifications')->nullable();
            $table->integer('cmp_maxdetmins')->nullable();
            $table->string('cmp_detcontacts', 1000)->nullable();
            $table->string('cmp_allowdetcharges', 1)->nullable();
            $table->string('cmp_maptuit_customnote', 512)->nullable();
            $table->integer('external_id')->nullable();
            $table->string('external_type', 6)->nullable();
            $table->string('cmp_TrlConfiguration', 6)->nullable();
            $table->string('cmp_service_location_qual', 1)->nullable();
            $table->string('cmp_service_location_own', 1)->nullable();
            $table->string('cmp_service_location_rating', 6)->nullable();
            $table->string('cmp_reftype_unique', 6)->nullable();
            $table->string('cmp_MileSearchLevel', 2)->nullable();
            $table->integer('cmp_det_start')->nullable();
            $table->string('cmp_det_apply_if_late', 1)->nullable();
            $table->integer('cmp_leadtime')->nullable();
            $table->string('cmp_railramp', 1)->nullable();
            $table->integer('cmp_PUPalert')->nullable();
            $table->integer('cmp_DRPalert')->nullable();
            $table->string('cmp_det_apply_if_early', 1)->nullable();
            $table->string('cmp_senddetalert', 1)->nullable();
            $table->string('cmp_athome_location', 1)->nullable();
            $table->string('cmp_thirdpartytype1', 8)->nullable();
            $table->string('cmp_thirdpartytype2', 8)->nullable();
            $table->string('cmp_aceidtype', 6)->nullable();
            $table->string('cmp_aceid', 30)->nullable();
            $table->integer('cmp_TMlatseconds')->nullable();
            $table->integer('cmp_TMlongseconds')->nullable();
            $table->decimal('cmp_TMdistancetolatlong', 9, 1)->nullable();
            $table->dateTime('cmp_TMlatlongdate')->nullable();
            $table->string('cmp_dimoverride', 1)->nullable();
            $table->string('cmp_overrideapplyhighestrate', 1)->nullable();
            $table->string('cmp_rbd_FlatRateOption', 10)->nullable();
            $table->decimal('cmp_MinLHAdj', 19, 4)->nullable();
            $table->string('cmp_RateBy', 1)->nullable();
            $table->string('cmp_rbd_highrateoption', 10)->nullable();
            $table->string('cmp_bookingterminal', 12);
            $table->string('cmp_supplier', 1)->nullable();
            $table->integer('cmp_ICaccessorial');
            $table->decimal('cmp_ICaccessorialfactor', 8, 4);
            $table->dateTime('cmp_last_call_date')->nullable();
            $table->string('cmp_last_call_note')->nullable();
            $table->string('cmp_last_call_user')->nullable();
            $table->dateTime('cmp_next_call_date')->nullable();
            $table->string('cmp_SchdEarliestDateOverride', 1)->nullable();
            $table->dateTime('cmp_GeoCodeRequested')->nullable();
            $table->integer('cmp_det_increment')->nullable();
            $table->string('cmp_det_rounding', 1)->nullable();
            $table->integer('cmp_det_threshold')->nullable();
            $table->string('cmp_det_override', 1)->nullable();
            $table->string('cmp_stop_events', 100)->nullable();
            $table->integer('cmp_freestops')->nullable();
            $table->string('cmp_stopevents_pay', 100)->nullable();
            $table->integer('cmp_freestops_pay')->nullable();
            $table->string('cmp_accountof', 1)->nullable();
            $table->integer('cmp_avgstopminutes')->nullable();
            $table->string('cmp_mailto_country', 50)->nullable();
            $table->string('cmp_billto_eligible_flag', 1)->nullable();
            $table->string('cmp_Payment_terms', 6)->nullable();
            $table->decimal('cmp_blended_min_qty', 19, 4)->nullable();
            $table->smallInteger('cmp_MonObsHolFlag')->nullable();
            $table->smallInteger('cmp_TueObsHolFlag')->nullable();
            $table->smallInteger('cmp_WedObsHolFlag')->nullable();
            $table->smallInteger('cmp_ThuObsHolFlag')->nullable();
            $table->smallInteger('cmp_FriObsHolFlag')->nullable();
            $table->smallInteger('cmp_SatObsHolFlag')->nullable();
            $table->smallInteger('cmp_SunObsHolFlag')->nullable();
            $table->smallInteger('cmp_FromHrDateAdj')->nullable();
            $table->string('cmp_minchargeoption', 30)->nullable();
            $table->string('cmp_acc_gvt_rpt', 50)->nullable();
            $table->string('cmp_acc_id', 15)->nullable();
            $table->string('cmp_BelongsTo', 6)->nullable();
            $table->integer('rhh_id')->nullable();
            $table->string('cmp_inv_toll_detail', 1)->nullable();
            $table->string('cmp_refnum_gpinvxfer', 20);
            $table->string('holiday_group', 6)->nullable();
            $table->string('cmp_refnum', 20)->nullable();
            $table->string('cmp_statemiletype1', 8)->nullable();
            $table->string('cmp_statemiletype2', 8)->nullable();
            $table->string('cmp_splitbillonrefnbr', 1)->nullable();
            $table->string('cmp_stp_type2', 6)->nullable();
            $table->string('cmp_stp_type3', 6)->nullable();
            $table->string('cmp_hiddenid', 1)->nullable();
            $table->string('cmp_firm_appt_value', 15)->nullable();
            $table->string('cmp_invoiceby', 3)->nullable();
            $table->string('cmp_volunits', 6)->nullable();
            $table->string('cmp_crmtype', 6)->nullable();
            $table->string('cmp_wgtunits', 6)->nullable();
            $table->string('cmp_rateallocation', 1)->nullable();
            $table->string('cmp_invoiceimageflag', 6)->nullable();
            $table->string('cmp_TollMethod', 6)->nullable();
            $table->string('cmp_AvgFuelPriceDateOverride', 1)->nullable();
            $table->string('cmp_refnum_gpdocdescxfer', 20);
            $table->integer('cmp_servicedrp_rpt')->nullable();
            $table->integer('cmp_servicepup_rpt')->nullable();
            $table->integer('cmp_servicebillto_rpt')->nullable();
            $table->integer('rowsec_rsrv_id')->nullable();
            $table->string('cmp_dedicated_bill', 1)->nullable();
            $table->string('cmp_house_number', 10)->nullable();
            $table->string('cmp_street_name', 90)->nullable();
            $table->string('cmp_inv_controlling_cmp_id', 8)->nullable();
            $table->string('cmp_inv_open_ivr_forward_number', 30)->nullable();
            $table->string('cmp_inv_closed_ivr_forward_number', 30)->nullable();
            $table->string('cmp_inv_numeric_id', 12)->nullable();
            $table->string('cmp_CreditHoldStatus', 6);
            $table->string('cmp_CreditHoldComment', 200)->nullable();
            $table->string('cmp_InvSrvReleaseOnly', 1);
            $table->string('cmp_InvSrvMode', 6);
            $table->string('cmp_ForecastBatch', 100)->nullable();
            $table->string('cmp_SalesHistoryBatch', 100)->nullable();
            $table->dateTime('cmp_ForecasterLastReadingDate')->nullable();
            $table->dateTime('cmp_ForecasterLastRunDate')->nullable();
            $table->string('cmp_TaxGroup', 6);
            $table->string('cmp_UseDips', 1);
            $table->string('cmp_sourcing_include_trans', 1);
            $table->string('cmp_sourcing_include_taxes', 1);
            $table->integer('cmp_sourcing_max_distance');
            $table->string('cmp_sourcing_quote_type', 6);
            $table->string('cmp_sourcing_quotebillto', 8);
            $table->string('cmp_sourcing_quotetransbillto', 8);
            $table->integer('cmp_ivr_pin')->nullable();
            $table->string('cmp_defaultstptype1', 6);
            $table->string('cmp_dedicated_usedate', 6)->nullable();
            $table->string('cmp_dedicated_datecycle', 6)->nullable();
            $table->string('cmp_timezone', 10)->nullable();
            $table->string('cmp_othertype3', 6)->nullable();
            $table->string('cmp_othertype4', 6)->nullable();
            $table->string('cmp_billing_rating_engine', 6)->nullable();
            $table->string('cmp_pophubmilesflag', 3)->nullable();
            $table->string('cmp_custequipprefix', 200)->nullable();
            $table->string('cmp_misc5', 254)->nullable();
            $table->string('cmp_misc6', 254)->nullable();
            $table->string('cmp_misc7', 254)->nullable();
            $table->string('cmp_misc8', 254)->nullable();
            $table->string('cmp_billto_spotquote', 8)->nullable();
            $table->tinyInteger('cmp_allow_tm_update')->nullable();
            $table->string('AppianDistanceFldData', 200)->nullable();
            $table->string('cmp_isbond', 1)->nullable();
            $table->string('cmp_invoice_when', 8)->nullable();
            $table->string('cmp_doublesdrop_location', 1)->nullable();
            $table->string('cmp_primaryflagrequired', 1)->nullable();
            $table->string('cmp_yard_type', 6)->nullable();
            $table->string('cmp_btm_toll_mileagetable', 2)->nullable();
            $table->string('cmp_terminal', 1)->nullable();
            $table->string('cmp_autobill', 1)->nullable();
            $table->string('cmp_autobill_terms', 24)->nullable();
            $table->string('cmp_useboldates', 1)->nullable();
            $table->string('cmp_sendarrivalalert', 1)->nullable();
            $table->string('cmp_senddeparturealert', 1)->nullable();
            $table->decimal('cmp_cmdvalue', 19, 4)->nullable();
            $table->string('cmp_mb_breaktype', 8)->nullable();
            $table->integer('cmp_mb_breakvalue')->nullable();
            $table->string('cmp_ar_transfer_nonbundled', 1)->nullable();
            $table->string('cmp_defaultcons', 8)->nullable();
            $table->string('cmp_mbdayofmonth', 3)->nullable();
            $table->string('cmp_RateEachPickDrop', 1)->nullable();
            $table->string('cmp_inv_audit', 1)->nullable();
            $table->string('cmp_app_eqcodes', 256)->nullable();
            $table->string('cmp_etawcbillto', 1)->nullable();
            $table->integer('trl_freedays');
            $table->decimal('trl_maxcharge', 19, 4)->nullable();
            $table->integer('cmp_DRBack')->nullable();
            $table->integer('cmp_DROut')->nullable();
            $table->string('cmp_dbh_custinvnum_prefix', 10)->nullable();
            $table->integer('cmp_dbh_custinvnum_startnum')->nullable();
            $table->tinyInteger('cmp_dbh_custinvnum_digits')->nullable();
            $table->string('cmp_ar_account', 66)->nullable();
            $table->string('cmp_ispreferred', 1)->nullable();
            $table->string('cmp_ImagingHandlingRebill', 6)->nullable();
            $table->string('cmp_ImagingHandlingMisc', 6)->nullable();
            $table->float('cmp_ctw_conv', 53, 0)->nullable();
            $table->float('cmp_ctw_break', 53, 0)->nullable();
            $table->float('cmp_wtc_conv', 53, 0)->nullable();
            $table->string('cmp_ctw_weightunits', 6)->nullable();
            $table->string('cmp_ctw_volumeunits', 6)->nullable();
            $table->dateTime('INS_TIMESTAMP');
        });
    }

    public function down(): void
    {
        Schema::connection('psbison')->dropIfExists('company');
    }
};
