<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('psbison')->create('legheader_active', function (Blueprint $table) {
            $table->integer('lgh_number');
            $table->integer('lgh_firstlegnumber')->nullable();
            $table->integer('lgh_lastlegnumber')->nullable();
            $table->integer('lgh_drvtripnumber')->nullable();
            $table->float('lgh_cost', 53, 0)->nullable();
            $table->float('lgh_revenue', 53, 0)->nullable();
            $table->integer('lgh_odometerstart')->nullable();
            $table->integer('lgh_odometerend')->nullable();
            $table->smallInteger('lgh_milesshortest')->nullable();
            $table->smallInteger('lgh_milespractical')->nullable();
            $table->float('lgh_allocfactor', 53, 0)->nullable();
            $table->dateTime('lgh_startdate')->nullable();
            $table->dateTime('lgh_enddate')->nullable();
            $table->integer('lgh_startcity')->nullable();
            $table->integer('lgh_endcity')->nullable();
            $table->string('lgh_startregion1', 6)->nullable();
            $table->string('lgh_endregion1', 6)->nullable();
            $table->string('lgh_startstate', 6)->nullable();
            $table->string('lgh_endstate', 6)->nullable();
            $table->string('lgh_outstatus', 6)->nullable();
            $table->integer('lgh_startlat')->nullable();
            $table->integer('lgh_startlong')->nullable();
            $table->integer('lgh_endlat')->nullable();
            $table->integer('lgh_endlong')->nullable();
            $table->string('lgh_class1', 6)->nullable();
            $table->string('lgh_class2', 6)->nullable();
            $table->string('lgh_class3', 6)->nullable();
            $table->string('lgh_class4', 6)->nullable();
            $table->integer('stp_number_start')->nullable();
            $table->integer('stp_number_end')->nullable();
            $table->string('cmp_id_start', 12)->nullable();
            $table->string('cmp_id_end', 12)->nullable();
            $table->string('lgh_startregion2', 6)->nullable();
            $table->string('lgh_startregion3', 6)->nullable();
            $table->string('lgh_startregion4', 6)->nullable();
            $table->string('lgh_endregion2', 6)->nullable();
            $table->string('lgh_endregion3', 6)->nullable();
            $table->string('lgh_endregion4', 6)->nullable();
            $table->string('lgh_instatus', 6)->nullable();
            $table->string('lgh_driver1', 8)->nullable();
            $table->string('lgh_driver2', 8)->nullable();
            $table->string('lgh_tractor', 8)->nullable();
            $table->string('lgh_primary_trailer', 13)->nullable();
            $table->integer('mov_number')->nullable();
            $table->integer('fgt_number')->nullable();
            $table->string('lgh_priority', 6)->nullable();
            $table->dateTime('lgh_schdtearliest')->nullable();
            $table->dateTime('lgh_schdtlatest')->nullable();
            $table->string('cmd_code', 8)->nullable();
            $table->string('fgt_description', 60)->nullable();
            $table->string('mpp_teamleader', 6)->nullable();
            $table->string('mpp_fleet', 6)->nullable();
            $table->string('mpp_division', 6)->nullable();
            $table->string('mpp_domicile', 6)->nullable();
            $table->string('mpp_company', 6)->nullable();
            $table->string('mpp_terminal', 6)->nullable();
            $table->string('mpp_type1', 6)->nullable();
            $table->string('mpp_type2', 6)->nullable();
            $table->string('mpp_type3', 6)->nullable();
            $table->string('mpp_type4', 6)->nullable();
            $table->string('trc_company', 6)->nullable();
            $table->string('trc_division', 6)->nullable();
            $table->string('trc_fleet', 6)->nullable();
            $table->string('trc_terminal', 6)->nullable();
            $table->string('trc_type1', 6)->nullable();
            $table->string('trc_type2', 6)->nullable();
            $table->string('trc_type3', 6)->nullable();
            $table->string('trc_type4', 6)->nullable();
            $table->integer('mfh_number')->nullable();
            $table->string('trl_company', 6)->nullable();
            $table->string('trl_fleet', 6)->nullable();
            $table->string('trl_division', 6)->nullable();
            $table->string('trl_terminal', 6)->nullable();
            $table->string('trl_type1', 6)->nullable();
            $table->string('trl_type2', 6)->nullable();
            $table->string('trl_type3', 6)->nullable();
            $table->string('trl_type4', 6)->nullable();
            $table->integer('ord_hdrnumber')->nullable();
            $table->string('timestamp')->nullable();
            $table->string('lgh_fueltaxstatus', 6)->nullable();
            $table->smallInteger('lgh_mtmiles')->nullable();
            $table->dateTime('lgh_prjdate1')->nullable();
            $table->string('lgh_etaalert1', 1)->nullable();
            $table->integer('lgh_etamins1')->nullable();
            $table->string('lgh_outofroute_routing', 1)->nullable();
            $table->string('lgh_type1', 6)->nullable();
            $table->decimal('lgh_alloc_revenue', 19, 4)->nullable();
            $table->string('lgh_primary_pup', 13)->nullable();
            $table->float('lgh_prod_hr', 53, 0)->nullable();
            $table->float('lgh_tot_hr', 53, 0)->nullable();
            $table->float('lgh_ld_unld_time', 53, 0)->nullable();
            $table->float('lgh_load_time', 53, 0)->nullable();
            $table->string('lgh_startcty_nmstct', 25)->nullable();
            $table->string('lgh_endcty_nmstct', 25)->nullable();
            $table->string('lgh_carrier', 8)->nullable();
            $table->dateTime('lgh_enddate_arrival')->nullable();
            $table->dateTime('lgh_dsp_date')->nullable();
            $table->dateTime('lgh_geo_date')->nullable();
            $table->string('lgh_nexttrailer1', 13)->nullable();
            $table->string('lgh_nexttrailer2', 13)->nullable();
            $table->integer('lgh_etamilestofinal')->nullable();
            $table->integer('lgh_etamintofinal')->nullable();
            $table->string('lgh_split_flag', 1)->nullable();
            $table->string('lgh_createdby', 128)->nullable();
            $table->dateTime('lgh_createdon')->nullable();
            $table->string('lgh_createapp', 128)->nullable();
            $table->string('lgh_updatedby', 128)->nullable();
            $table->dateTime('lgh_updatedon')->nullable();
            $table->string('lgh_updateapp', 128)->nullable();
            $table->dateTime('lgh_rstartdate')->nullable();
            $table->dateTime('lgh_renddate')->nullable();
            $table->integer('lgh_rstartcity')->nullable();
            $table->integer('lgh_rendcity')->nullable();
            $table->string('lgh_rstartregion1', 6)->nullable();
            $table->string('lgh_rendregion1', 6)->nullable();
            $table->string('lgh_rstartstate', 6)->nullable();
            $table->string('lgh_rendstate', 6)->nullable();
            $table->integer('lgh_rstartlat')->nullable();
            $table->integer('lgh_rstartlong')->nullable();
            $table->integer('lgh_rendlat')->nullable();
            $table->integer('lgh_rendlong')->nullable();
            $table->integer('stp_number_rstart')->nullable();
            $table->integer('stp_number_rend')->nullable();
            $table->string('cmp_id_rstart', 12)->nullable();
            $table->string('cmp_id_rend', 12)->nullable();
            $table->string('lgh_rstartregion2', 6)->nullable();
            $table->string('lgh_rstartregion3', 6)->nullable();
            $table->string('lgh_rstartregion4', 6)->nullable();
            $table->string('lgh_rendregion2', 6)->nullable();
            $table->string('lgh_rendregion3', 6)->nullable();
            $table->string('lgh_rendregion4', 6)->nullable();
            $table->string('lgh_rstartcty_nmstct', 25)->nullable();
            $table->string('lgh_rendcty_nmstct', 25)->nullable();
            $table->smallInteger('lgh_feetavailable')->nullable();
            $table->dateTime('can_cap_expires')->nullable();
            $table->dateTime('can_ld_expires')->nullable();
            $table->dateTime('lgh_dispatchdate')->nullable();
            $table->string('lgh_asset_lock', 1)->nullable();
            $table->dateTime('lgh_asset_lock_dtm')->nullable();
            $table->string('lgh_asset_lock_user', 20)->nullable();
            $table->string('lgh_load_origin', 12)->nullable();
            $table->float('lgh_est_lhrate', 53, 0)->nullable();
            $table->float('lgh_est_lhpay', 53, 0)->nullable();
            $table->float('lgh_est_dhrate', 53, 0)->nullable();
            $table->float('lgh_est_dhpay', 53, 0)->nullable();
            $table->float('lgh_est_accessorials', 53, 0)->nullable();
            $table->integer('drvplan_number')->nullable();
            $table->integer('next_drp_stp_number')->nullable();
            $table->integer('next_pup_stp_number')->nullable();
            $table->integer('ord_totalweight')->nullable();
            $table->integer('ord_totalvolume')->nullable();
            $table->integer('tot_count')->nullable();
            $table->integer('cmd_count')->nullable();
            $table->smallInteger('ordercount')->nullable();
            $table->integer('xdock')->nullable();
            $table->tinyInteger('ord_stopcount')->nullable();
            $table->string('washstatus', 1)->nullable();
            $table->string('ref_type', 6)->nullable();
            $table->string('ref_number', 30)->nullable();
            $table->string('npup_cmpid', 8)->nullable();
            $table->string('npup_cmpname', 30)->nullable();
            $table->string('npup_ctyname', 25)->nullable();
            $table->string('npup_state', 6)->nullable();
            $table->dateTime('npup_arrivaldate')->nullable();
            $table->string('ndrp_cmpid', 8)->nullable();
            $table->string('ndrp_cmpname', 30)->nullable();
            $table->string('ndrp_ctyname', 25)->nullable();
            $table->string('ndrp_state', 6)->nullable();
            $table->dateTime('ndrp_arrivaldate')->nullable();
            $table->dateTime('npup_departuredate')->nullable();
            $table->dateTime('ndrp_departuredate')->nullable();
            $table->string('lgh_type2', 6)->nullable();
            $table->string('lgh_extrainfo1')->nullable();
            $table->string('lgh_extrainfo2', 30)->nullable();
            $table->string('lgh_extrainfo3', 30)->nullable();
            $table->string('lgh_extrainfo4', 30)->nullable();
            $table->string('lgh_extrainfo5', 30)->nullable();
            $table->string('lgh_extrainfo6', 30)->nullable();
            $table->string('lgh_extrainfo7', 30)->nullable();
            $table->string('lgh_extrainfo8', 30)->nullable();
            $table->string('lgh_extrainfo9', 30)->nullable();
            $table->string('lgh_extrainfo10', 30)->nullable();
            $table->string('lgh_extrainfo11', 30)->nullable();
            $table->string('lgh_extrainfo12', 30)->nullable();
            $table->string('lgh_extrainfo13', 30)->nullable();
            $table->string('lgh_extrainfo14', 30)->nullable();
            $table->string('lgh_extrainfo15', 30)->nullable();
            $table->string('lgh_tm_status', 6)->nullable();
            $table->integer('lgh_tour_number')->nullable();
            $table->string('o_cmpname', 30)->nullable();
            $table->string('o_state', 6)->nullable();
            $table->string('d_cmpname', 30)->nullable();
            $table->string('d_state', 6)->nullable();
            $table->string('f_cmpid', 8)->nullable();
            $table->string('f_cmpname', 30)->nullable();
            $table->string('f_ctyname', 25)->nullable();
            $table->string('f_state', 6)->nullable();
            $table->string('l_cmpid', 8)->nullable();
            $table->string('l_cmpname', 30)->nullable();
            $table->string('l_ctyname', 25)->nullable();
            $table->string('l_state', 6)->nullable();
            $table->string('evt_driver1_name', 45)->nullable();
            $table->string('evt_driver2_name', 45)->nullable();
            $table->string('lgh_outstatus_name', 20)->nullable();
            $table->string('lgh_instatus_name', 20)->nullable();
            $table->string('lgh_priority_name', 20)->nullable();
            $table->string('trl_type1_name', 20)->nullable();
            $table->string('lgh_class1_name', 20)->nullable();
            $table->string('lgh_class2_name', 20)->nullable();
            $table->string('lgh_class3_name', 20)->nullable();
            $table->string('lgh_class4_name', 20)->nullable();
            $table->string('opt_trc_type4_label', 20)->nullable();
            $table->string('opt_trl_type4_label', 20)->nullable();
            $table->string('c_lgh_type1', 20)->nullable();
            $table->string('c_lgh_type2', 20)->nullable();
            $table->string('mpp_fleet_name', 20)->nullable();
            $table->string('ord_ord_subcompany', 8)->nullable();
            $table->string('ord_bookedby', 20)->nullable();
            $table->string('ord_trl_type1', 6)->nullable();
            $table->integer('ord_totalmiles')->nullable();
            $table->string('o_cmp_geoloc', 50)->nullable();
            $table->string('d_cmp_geoloc', 50)->nullable();
            $table->string('d_address1', 40)->nullable();
            $table->string('d_address2', 40)->nullable();
            $table->string('bison_latereason', 80)->nullable();
            $table->string('bison_latestatus', 10)->nullable();
            $table->string('lgh_reftype', 6)->nullable();
            $table->string('lgh_refnum', 30)->nullable();
            $table->string('trc_type1name', 20)->nullable();
            $table->string('trc_type2name', 20)->nullable();
            $table->string('trc_type3name', 20)->nullable();
            $table->string('trc_type4name', 20)->nullable();
            $table->string('next_stp_event_code', 6)->nullable();
            $table->string('next_stop_of_total', 10)->nullable();
            $table->string('lgh_comment')->nullable();
            $table->integer('lgh_miles')->nullable();
            $table->float('lgh_linehaul', 53, 0)->nullable();
            $table->float('lgh_ord_charge', 53, 0)->nullable();
            $table->float('lgh_act_weight', 53, 0)->nullable();
            $table->float('lgh_est_weight', 53, 0)->nullable();
            $table->float('lgh_tot_weight', 53, 0)->nullable();
            $table->string('lgh_max_weight_exceeded', 1)->nullable();
            $table->integer('lgh_detstatus')->nullable();
            $table->integer('lgh_tmstatusstopnumber')->nullable();
            $table->string('lgh_tm_statusname', 20)->nullable();
            $table->string('ord_billto', 8)->nullable();
            $table->string('lgh_order_source', 6)->nullable();
            $table->string('lgh_washplan', 20)->nullable();
            $table->string('lgh_hzd_cmd_class', 8)->nullable();
            $table->string('ord_company', 8)->nullable();
            $table->string('lgh_originzip', 10)->nullable();
            $table->string('lgh_destzip', 10)->nullable();
            $table->string('lgh_route', 15)->nullable();
            $table->string('lgh_booked_revtype1', 12)->nullable();
            $table->string('lgh_204status', 30)->nullable();
            $table->dateTime('lgh_204date')->nullable();
            $table->string('lgh_permit_status', 6)->nullable();
            $table->string('lgh_trc_comment')->nullable();
            $table->string('lgh_ace_status', 6)->nullable();
            $table->string('next_ndrp_cmpid', 8)->nullable();
            $table->string('next_ndrp_cmpname', 30)->nullable();
            $table->string('next_ndrp_ctyname', 25)->nullable();
            $table->string('next_ndrp_state', 6)->nullable();
            $table->dateTime('next_ndrp_arrivaldate')->nullable();
            $table->string('lgh_ace_status_name', 20)->nullable();
            $table->string('lgh_chassis', 13)->nullable();
            $table->string('lgh_chassis2', 13)->nullable();
            $table->string('lgh_204_tradingpartner', 20)->nullable();
            $table->integer('lgh_total_mov_bill_miles')->nullable();
            $table->integer('lgh_total_mov_miles')->nullable();
            $table->string('lgh_mile_overage_message', 64)->nullable();
            $table->decimal('lgh_car_rate', 19, 4)->nullable();
            $table->decimal('lgh_car_charge', 19, 4)->nullable();
            $table->decimal('lgh_car_accessorials', 12, 4)->nullable();
            $table->decimal('lgh_car_totalcharge', 19, 4)->nullable();
            $table->string('lgh_recommended_car_id', 8)->nullable();
            $table->string('lgh_spot_rate_updatedby', 20)->nullable();
            $table->dateTime('lgh_spot_rate_updateddt')->nullable();
            $table->string('lgh_spot_rate', 1)->nullable();
            $table->string('lgh_ship_status', 6)->nullable();
            $table->decimal('lgh_protected_rate', 19, 4)->nullable();
            $table->decimal('lgh_avg_rate', 19, 4)->nullable();
            $table->string('lgh_edi_counter', 30)->nullable();
            $table->string('lgh_faxemail_created', 1)->nullable();
            $table->integer('lgh_externalrating_miles')->nullable();
            $table->decimal('lgh_acc_fsc', 19, 4)->nullable();
            $table->string('lgh_prev_seg_status', 6)->nullable();
            $table->dateTime('lgh_prev_seg_status_last_updated')->nullable();
            $table->string('lgh_raildispatchstatus', 6)->nullable();
            $table->bigInteger('ma_transaction_id')->nullable();
            $table->integer('ma_tour_number')->nullable();
            $table->tinyInteger('ma_tour_sequence')->nullable();
            $table->tinyInteger('ma_tour_max_sequence')->nullable();
            $table->string('ma_mpp_id', 8)->nullable();
            $table->string('ma_trc_number', 8)->nullable();
            $table->integer('ma_lgh_number')->nullable();
            $table->string('lgh_dolly', 13)->nullable();
            $table->string('lgh_dolly2', 13)->nullable();
            $table->string('lgh_trailer3', 13)->nullable();
            $table->string('lgh_trailer4', 13)->nullable();
            $table->string('lgh_other_status1', 6)->nullable();
            $table->string('lgh_other_status2', 6)->nullable();
            $table->string('lgh_direct_route_status1', 6)->nullable();
            $table->string('trc_teamleader', 6)->nullable();
            $table->string('lgh_optimizestatus', 1)->nullable();
            $table->integer('lgh_optimizedrouteid')->nullable();
            $table->float('lgh_autoloadmaxgvw', 53, 0)->nullable();
            $table->string('lgh_drv_tndr_status', 8)->nullable();
        });
    }

    public function down(): void
    {
        Schema::connection('psbison')->dropIfExists('legheader_active');
    }
};
