<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('psbison')->create('stops', function (Blueprint $table) {
            $table->integer('ord_hdrnumber');
            $table->integer('stp_number');
            $table->string('cmp_id', 8)->nullable();
            $table->string('stp_region1', 6)->nullable();
            $table->string('stp_region2', 6)->nullable();
            $table->string('stp_region3', 6)->nullable();
            $table->integer('stp_city');
            $table->string('stp_state', 6)->nullable();
            $table->dateTime('stp_schdtearliest')->nullable();
            $table->dateTime('stp_origschdt')->nullable();
            $table->dateTime('stp_arrivaldate')->nullable();
            $table->dateTime('stp_departuredate')->nullable();
            $table->string('stp_reasonlate', 6)->nullable();
            $table->dateTime('stp_schdtlatest')->nullable();
            $table->integer('lgh_number')->nullable();
            $table->integer('mfh_number')->nullable();
            $table->string('stp_type', 6)->nullable();
            $table->string('stp_paylegpt', 1)->nullable();
            $table->integer('shp_hdrnumber')->nullable();
            $table->integer('stp_sequence')->nullable();
            $table->string('stp_region4', 6)->nullable();
            $table->integer('stp_lgh_sequence')->nullable();
            $table->string('trl_id', 13)->nullable();
            $table->integer('stp_mfh_sequence')->nullable();
            $table->string('stp_event', 6)->nullable();
            $table->string('stp_mfh_position', 6)->nullable();
            $table->string('stp_lgh_position', 6)->nullable();
            $table->string('stp_mfh_status', 6)->nullable();
            $table->string('stp_lgh_status', 6)->nullable();
            $table->integer('stp_ord_mileage')->nullable();
            $table->integer('stp_lgh_mileage')->nullable();
            $table->integer('stp_mfh_mileage')->nullable();
            $table->integer('mov_number')->nullable();
            $table->string('timestamp')->nullable();
            $table->string('stp_loadstatus', 3)->nullable();
            $table->float('stp_weight', 53, 0)->nullable();
            $table->string('stp_weightunit', 6)->nullable();
            $table->string('cmd_code', 8)->nullable();
            $table->string('stp_description', 60)->nullable();
            $table->decimal('stp_count', 10)->nullable();
            $table->string('stp_countunit', 10)->nullable();
            $table->string('cmp_name', 30)->nullable();
            $table->string('stp_comment', 254)->nullable();
            $table->string('stp_status', 6)->nullable();
            $table->string('stp_reftype', 6)->nullable();
            $table->string('stp_refnum', 30)->nullable();
            $table->string('stp_reasonlate_depart', 6)->nullable();
            $table->string('stp_screenmode', 6)->nullable();
            $table->tinyInteger('skip_trigger')->nullable();
            $table->float('stp_volume', 53, 0)->nullable();
            $table->string('stp_volumeunit', 6)->nullable();
            $table->integer('stp_dispatched_sequence')->nullable();
            $table->string('stp_arr_confirmed', 1)->nullable();
            $table->string('stp_dep_confirmed', 1)->nullable();
            $table->string('stp_type1', 6);
            $table->string('stp_redeliver', 1)->nullable();
            $table->string('stp_osd', 1)->nullable();
            $table->string('stp_pudelpref', 10)->nullable();
            $table->string('stp_phonenumber', 20)->nullable();
            $table->float('stp_delayhours', 53, 0)->nullable();
            $table->float('stp_ooa_mileage', 53, 0)->nullable();
            $table->string('stp_zipcode', 10)->nullable();
            $table->integer('stp_OOA_stop')->nullable();
            $table->string('stp_address', 40)->nullable();
            $table->integer('stp_transfer_stp')->nullable();
            $table->string('stp_phonenumber2', 20)->nullable();
            $table->string('stp_address2', 40)->nullable();
            $table->string('stp_contact', 30)->nullable();
            $table->string('stp_podname', 20)->nullable();
            $table->dateTime('stp_custpickupdate')->nullable();
            $table->dateTime('stp_custdeliverydate')->nullable();
            $table->integer('stp_cmp_close')->nullable();
            $table->dateTime('stp_activitystart_dt')->nullable();
            $table->dateTime('stp_activityend_dt')->nullable();
            $table->string('stp_departure_status', 6)->nullable();
            $table->dateTime('stp_eta')->nullable();
            $table->dateTime('stp_etd')->nullable();
            $table->string('stp_transfer_type', 3)->nullable();
            $table->integer('stp_trip_mileage')->nullable();
            $table->string('stp_stl_mileage_flag', 1)->nullable();
            $table->integer('tmp_evt_number')->nullable();
            $table->integer('tmp_fgt_number')->nullable();
            $table->integer('stp_pallets_in')->nullable();
            $table->integer('stp_pallets_out')->nullable();
            $table->integer('stp_pallets_received')->nullable();
            $table->integer('stp_pallets_shipped')->nullable();
            $table->integer('stp_pallets_rejected')->nullable();
            $table->integer('psh_number')->nullable();
            $table->integer('stp_dispatched_status')->nullable();
            $table->string('stp_reasonlate_text')->nullable();
            $table->string('stp_reasonlate_depart_text')->nullable();
            $table->integer('stp_advreturnempty')->nullable();
            $table->string('stp_country', 50)->nullable();
            $table->decimal('stp_loadingmeters', 12, 4)->nullable();
            $table->string('stp_loadingmetersunit', 6)->nullable();
            $table->decimal('stp_cod_amount')->nullable();
            $table->string('stp_cod_currency', 6)->nullable();
            $table->float('stp_extra_count', null, 0)->nullable();
            $table->float('stp_extra_weight', 53, 0)->nullable();
            $table->tinyInteger('bison_appt')->nullable();
            $table->string('stp_tmstatus', 6)->nullable();
            $table->integer('stp_detstatus')->nullable();
            $table->integer('stp_alloweddet')->nullable();
            $table->decimal('stp_gfc_arr_radius', 7)->nullable();
            $table->string('stp_gfc_arr_radiusunits', 6)->nullable();
            $table->integer('stp_gfc_arr_timeout')->nullable();
            $table->integer('stp_est_drv_time')->nullable();
            $table->integer('stp_est_activity')->nullable();
            $table->integer('nlm_time_diff')->nullable();
            $table->decimal('stp_gfc_arv_radiusMiles', 7)->nullable();
            $table->decimal('stp_gfc_dep_radiusMiles', 7)->nullable();
            $table->decimal('stp_gfc_lat', 12, 4)->nullable();
            $table->decimal('stp_gfc_long', 12, 4)->nullable();
            $table->dateTime('stp_aad_arvTime')->nullable();
            $table->integer('stp_aad_arvConfidence')->nullable();
            $table->dateTime('stp_aad_depTime')->nullable();
            $table->integer('stp_aad_depConfidence')->nullable();
            $table->decimal('stp_aad_lastckc_lat', 12, 4)->nullable();
            $table->decimal('stp_aad_lastckc_long', 12, 4)->nullable();
            $table->dateTime('stp_aad_lastckc_time')->nullable();
            $table->integer('stp_aad_lastckc_tripStatus')->nullable();
            $table->decimal('stp_aad_laststartckc_lat', 12, 4)->nullable();
            $table->decimal('stp_aad_laststartckc_long', 12, 4)->nullable();
            $table->dateTime('stp_aad_laststartckc_time')->nullable();
            $table->integer('stp_aad_laststartckc_tripStatus')->nullable();
            $table->decimal('stp_aad_arvckc_lat', 12, 4)->nullable();
            $table->decimal('stp_aad_arvckc_long', 12, 4)->nullable();
            $table->dateTime('stp_aad_arvckc_time')->nullable();
            $table->integer('stp_aad_arvckc_tripStatus')->nullable();
            $table->decimal('stp_aad_depckc_lat', 12, 4)->nullable();
            $table->decimal('stp_aad_depckc_long', 12, 4)->nullable();
            $table->dateTime('stp_aad_depckc_time')->nullable();
            $table->integer('stp_aad_depckc_tripStatus')->nullable();
            $table->string('last_updateby', 256)->nullable();
            $table->dateTime('last_updatedate')->nullable();
            $table->integer('stp_lgh_mileage_mtid')->nullable();
            $table->decimal('stp_count2', 10)->nullable();
            $table->string('stp_countunit2', 10)->nullable();
            $table->decimal('stp_ord_toll_cost', 19, 4)->nullable();
            $table->integer('stp_ord_mileage_mtid')->nullable();
            $table->integer('stp_ooa_mileage_mtid')->nullable();
            $table->string('last_updatebydepart', 256)->nullable();
            $table->dateTime('last_updatedatedepart')->nullable();
            $table->string('stp_unload_paytype', 6)->nullable();
            $table->string('stp_transferred', 1)->nullable();
            $table->dateTime('stp_GeoCodeRequested')->nullable();
            $table->integer('stp_reasonlate_min')->nullable();
            $table->integer('stp_reasonlate_depart_min')->nullable();
            $table->integer('stp_lgh_mileage_stlrate')->nullable();
            $table->integer('stp_ord_mileage_stlrate')->nullable();
            $table->dateTime('stp_rescheduledate')->nullable();
            $table->string('stp_showas_cmpid', 8)->nullable();
            $table->dateTime('stp_origarrival')->nullable();
            $table->string('stp_type2', 6)->nullable();
            $table->string('stp_type3', 6)->nullable();
            $table->string('stp_timewindow', 15)->nullable();
            $table->string('stp_firm_appt_flag', 1)->nullable();
            $table->string('stp_delay_eligible', 1)->nullable();
            $table->string('stp_mileagetype', 6);
            $table->integer('stp_ico_stp_number_child')->nullable();
            $table->integer('stp_span_days')->nullable();
            $table->string('stp_AppointmentStatus', 6)->nullable();
            $table->string('RailServiceLevel', 6)->nullable();
            $table->dateTime('stp_CustomerRequestDate')->nullable();
            $table->decimal('stp_rpt_miles', 7)->nullable();
            $table->integer('stp_rpt_miles_mtid')->nullable();
            $table->string('stp_empty_split', 1)->nullable();
            $table->dateTime('stp_optimizationdate')->nullable();
            $table->integer('stp_ico_stp_number_parent')->nullable();
            $table->string('stp_app_eqcodes', 256)->nullable();
            $table->string('trl_id2', 13)->nullable();
            $table->string('trl_id3', 13)->nullable();
            $table->dateTime('INS_TIMESTAMP');
        });
    }

    public function down(): void
    {
        Schema::connection('psbison')->dropIfExists('stops');
    }
};
