<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('psbison')->create('invoiceheader', function (Blueprint $table) {
            $table->string('ivh_invoicenumber', 12);
            $table->string('ivh_billto', 8)->nullable();
            $table->string('ivh_terms', 3)->nullable();
            $table->decimal('ivh_totalcharge', 19, 4)->nullable();
            $table->string('ivh_shipper', 8)->nullable();
            $table->string('ivh_consignee', 8)->nullable();
            $table->string('ivh_originpoint', 8)->nullable();
            $table->string('ivh_destpoint', 8)->nullable();
            $table->string('ivh_invoicestatus', 6)->nullable();
            $table->integer('ivh_origincity')->nullable();
            $table->integer('ivh_destcity')->nullable();
            $table->string('ivh_originstate', 2)->nullable();
            $table->string('ivh_deststate', 2)->nullable();
            $table->string('ivh_originregion1', 6)->nullable();
            $table->string('ivh_destregion1', 6)->nullable();
            $table->string('ivh_supplier', 8)->nullable();
            $table->dateTime('ivh_shipdate')->nullable();
            $table->dateTime('ivh_deliverydate')->nullable();
            $table->string('ivh_revtype1', 6)->nullable();
            $table->string('ivh_revtype2', 6)->nullable();
            $table->string('ivh_revtype3', 6)->nullable();
            $table->string('ivh_revtype4', 6)->nullable();
            $table->float('ivh_totalweight', 53, 0)->nullable();
            $table->float('ivh_totalpieces', 53, 0)->nullable();
            $table->float('ivh_totalmiles', 53, 0)->nullable();
            $table->string('ivh_currency', 6)->nullable();
            $table->dateTime('ivh_currencydate')->nullable();
            $table->float('ivh_totalvolume', 53, 0)->nullable();
            $table->decimal('ivh_taxamount1', 19, 4)->nullable();
            $table->decimal('ivh_taxamount2', 19, 4)->nullable();
            $table->decimal('ivh_taxamount3', 19, 4)->nullable();
            $table->decimal('ivh_taxamount4', 19, 4)->nullable();
            $table->string('ivh_transtype', 6)->nullable();
            $table->string('ivh_creditmemo', 1)->nullable();
            $table->string('ivh_applyto', 12)->nullable();
            $table->integer('shp_hdrnumber')->nullable();
            $table->dateTime('ivh_printdate')->nullable();
            $table->dateTime('ivh_billdate')->nullable();
            $table->dateTime('ivh_lastprintdate')->nullable();
            $table->integer('ivh_hdrnumber');
            $table->integer('ord_hdrnumber')->nullable();
            $table->string('ivh_originregion2', 6)->nullable();
            $table->string('ivh_originregion3', 6)->nullable();
            $table->string('ivh_originregion4', 6)->nullable();
            $table->string('ivh_destregion2', 6)->nullable();
            $table->string('ivh_destregion3', 6)->nullable();
            $table->string('ivh_destregion4', 6)->nullable();
            $table->integer('mfh_hdrnumber')->nullable();
            $table->string('ivh_remark', 254)->nullable();
            $table->string('ivh_driver', 8)->nullable();
            $table->string('ivh_tractor', 8)->nullable();
            $table->string('ivh_trailer', 13)->nullable();
            $table->string('ivh_user_id1', 20)->nullable();
            $table->string('ivh_user_id2', 20)->nullable();
            $table->string('ivh_ref_number', 30)->nullable();
            $table->string('ivh_driver2', 8)->nullable();
            $table->integer('mov_number')->nullable();
            $table->string('timestamp')->nullable();
            $table->string('ivh_edi_flag', 30)->nullable();
            $table->float('ivh_freight_miles', 53, 0)->nullable();
            $table->string('ivh_priority', 6)->nullable();
            $table->smallInteger('ivh_low_temp')->nullable();
            $table->smallInteger('ivh_high_temp')->nullable();
            $table->dateTime('ivh_xferdate')->nullable();
            $table->string('ivh_order_by', 8)->nullable();
            $table->string('tar_tarriffnumber', 12)->nullable();
            $table->integer('tar_number')->nullable();
            $table->tinyInteger('ivh_bookyear')->nullable();
            $table->tinyInteger('ivh_bookmonth')->nullable();
            $table->string('tar_tariffitem', 12)->nullable();
            $table->decimal('ivh_maxlength', 19, 4)->nullable();
            $table->decimal('ivh_maxwidth', 19, 4)->nullable();
            $table->decimal('ivh_maxheight', 19, 4)->nullable();
            $table->string('ivh_mbstatus', 6)->nullable();
            $table->integer('ivh_mbnumber')->nullable();
            $table->string('ord_number', 12)->nullable();
            $table->float('ivh_quantity', 53, 0)->nullable();
            $table->decimal('ivh_rate', 19, 4)->nullable();
            $table->decimal('ivh_charge', 19, 4)->nullable();
            $table->string('cht_itemcode', 6)->nullable();
            $table->string('ivh_splitbill_flag', 1)->nullable();
            $table->string('ivh_company', 6)->nullable();
            $table->string('ivh_carrier', 8)->nullable();
            $table->decimal('ivh_archarge', 19, 4)->nullable();
            $table->string('ivh_arcurrency', 6)->nullable();
            $table->float('ivh_loadtime', 53, 0)->nullable();
            $table->float('ivh_unloadtime', 53, 0)->nullable();
            $table->float('ivh_drivetime', 53, 0)->nullable();
            $table->float('ivh_totaltime', 53, 0)->nullable();
            $table->string('ivh_rateby', 1)->nullable();
            $table->dateTime('ivh_revenue_date')->nullable();
            $table->string('ivh_batch_id', 10)->nullable();
            $table->smallInteger('ivh_stopoffs')->nullable();
            $table->smallInteger('Ivh_quantity_type')->nullable();
            $table->smallInteger('ivh_charge_type')->nullable();
            $table->string('ivh_originzipcode', 10)->nullable();
            $table->string('ivh_destzipcode', 10)->nullable();
            $table->float('ivh_ratingquantity', 53, 0)->nullable();
            $table->string('ivh_ratingunit', 6)->nullable();
            $table->string('ivh_unit', 6)->nullable();
            $table->float('ivh_totalfsc', 53, 0)->nullable();
            $table->decimal('ivh_mileage_adjustment', 9, 1)->nullable();
            $table->string('ivh_definition', 6)->nullable();
            $table->string('ivh_hideshipperaddr', 1)->nullable();
            $table->string('ivh_hideconsignaddr', 1)->nullable();
            $table->string('ivh_paperworkstatus', 6)->nullable();
            $table->string('ivh_showshipper', 8)->nullable();
            $table->string('ivh_showcons', 8)->nullable();
            $table->decimal('ivh_allinclusivecharge', 19, 4)->nullable();
            $table->string('ivh_order_cmd_code', 8)->nullable();
            $table->string('ivh_applyto_definition', 6)->nullable();
            $table->string('ivh_reftype', 6)->nullable();
            $table->string('ivh_attention', 254)->nullable();
            $table->smallInteger('ivh_rate_type')->nullable();
            $table->string('ivh_paperwork_override', 1)->nullable();
            $table->integer('ivh_cmrbill_link')->nullable();
            $table->dateTime('ivh_mbperiod')->nullable();
            $table->dateTime('ivh_mbperiodstart')->nullable();
            $table->tinyInteger('ivh_imagestatus')->nullable();
            $table->dateTime('ivh_imagestatus_date')->nullable();
            $table->smallInteger('ivh_imagecount')->nullable();
            $table->tinyInteger('ivh_mbimagestatus')->nullable();
            $table->dateTime('ivh_mbimagestatus_date')->nullable();
            $table->smallInteger('ivh_mbimagecount')->nullable();
            $table->string('last_updateby', 256)->nullable();
            $table->dateTime('last_updatedate')->nullable();
            $table->decimal('ivh_mileage_adj_pct', 9)->nullable();
            $table->integer('inv_revenue_pay_fix')->nullable();
            $table->decimal('inv_revenue_pay', 19, 4)->nullable();
            $table->string('ivh_billto_parent', 8)->nullable();
            $table->string('ivh_block_printing', 1)->nullable();
            $table->integer('ivh_custdoc')->nullable();
            $table->string('ivh_entryport', 8);
            $table->string('ivh_exitport', 8);
            $table->decimal('ivh_paid_amount', 19, 4)->nullable();
            $table->string('ivh_pay_status', 1)->nullable();
            $table->decimal('ivh_dimfactor', 12, 4)->nullable();
            $table->string('ivh_TrlConfiguration', 6)->nullable();
            $table->string('ivh_order_source', 6)->nullable();
            $table->decimal('ivh_fuelprice', 19, 4)->nullable();
            $table->dateTime('ivh_gp_gl_postdate');
            $table->smallInteger('ivh_charge_type_lh')->nullable();
            $table->string('ivh_booked_revtype1', 12)->nullable();
            $table->string('ivh_misc_number', 12)->nullable();
            $table->string('ivh_paid_indicator', 1)->nullable();
            $table->string('ivh_lastchecknumber', 25)->nullable();
            $table->decimal('ivh_lastcheckamount', 19, 4)->nullable();
            $table->decimal('ivh_totalpaid', 19, 4)->nullable();
            $table->dateTime('ivh_lastcheckdate')->nullable();
            $table->decimal('ivh_exchangerate', 19, 4)->nullable();
            $table->float('ivh_loaded_distance', 53, 0)->nullable();
            $table->float('ivh_empty_distance', 53, 0)->nullable();
            $table->string('ivh_BelongsTo', 6)->nullable();
            $table->integer('ivh_leaseid')->nullable();
            $table->dateTime('ivh_leaseperiodenddate')->nullable();
            $table->string('ivh_nomincharges', 1)->nullable();
            $table->integer('car_key')->nullable();
            $table->string('ivh_furthestpointconsignee', 8)->nullable();
            $table->string('ivh_invoiceby', 3)->nullable();
            $table->integer('ivh_mbnumber_custom')->nullable();
            $table->string('ivh_trailer2', 13)->nullable();
            $table->string('ivh_GPDatabase', 25)->nullable();
            $table->string('ivh_GPserver', 25)->nullable();
            $table->string('ivh_GPTerritory', 25)->nullable();
            $table->string('ivh_GPSalesPerson', 25)->nullable();
            $table->string('ivh_GPPONumber', 25)->nullable();
            $table->string('ivh_GPDocDescription', 25)->nullable();
            $table->string('ivh_GPCustNumber', 25)->nullable();
            $table->string('ivh_GPDocnumber', 25)->nullable();
            $table->string('ivh_GPbachnumbeer', 25)->nullable();
            $table->dateTime('ivh_GPbilldate')->nullable();
            $table->dateTime('ivh_GPDuedate')->nullable();
            $table->dateTime('ivh_GPpostdate')->nullable();
            $table->integer('ivh_docnumber')->nullable();
            $table->integer('rowsec_rsrv_id')->nullable();
            $table->integer('dbh_id')->nullable();
            $table->dateTime('ivh_billing_usedate')->nullable();
            $table->string('ivh_billing_usedate_setting', 6)->nullable();
            $table->integer('ivh_dedicated_invnumber')->nullable();
            $table->string('posted_ind', 1)->nullable();
            $table->string('ivh_splitgroup', 6)->nullable();
            $table->string('mbgroupdata', 10)->nullable();
            $table->string('ivh_reprint', 1)->nullable();
            $table->string('ivh_mb_customgroupby', 80)->nullable();
            $table->string('ivh_dballocate_flag', 1)->nullable();
            $table->string('ivh_donotprint', 1)->nullable();
            $table->string('ivh_subcompany', 8)->nullable();
            $table->dateTime('ivh_dedicated_includedate')->nullable();
            $table->decimal('ivh_lh_charge_with_rollin', 19, 4)->nullable();
            $table->decimal('ivh_rollin_lh_rate', 19, 4)->nullable();
            $table->decimal('ivh_lh_charge', 19, 4)->nullable();
            $table->float('ivh_totalpallets', 53, 0)->nullable();
            $table->string('ivh_totalpalletunits', 6)->nullable();
            $table->string('ivh_totalweightunits', 6)->nullable();
            $table->string('ivh_totalvolumeunits', 6)->nullable();
            $table->string('ivh_totalpiecesunits', 6)->nullable();
            $table->string('ivh_totalmilesunits', 6)->nullable();
            $table->dateTime('INS_TIMESTAMP');
        });
    }

    public function down(): void
    {
        Schema::connection('psbison')->dropIfExists('invoiceheader');
    }
};
