<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('psbison')->create('paydetail', function (Blueprint $table) {
            $table->binary('timestamp')->nullable();
            $table->integer('pyd_number');
            $table->integer('pyh_number')->nullable();
            $table->integer('lgh_number')->nullable();
            $table->integer('asgn_number')->nullable();
            $table->string('asgn_type', 6)->nullable();
            $table->string('asgn_id', 13)->nullable();
            $table->integer('ivd_number')->nullable();
            $table->string('pyd_prorap', 1)->nullable();
            $table->string('pyd_payto', 12)->nullable();
            $table->string('pyt_itemcode', 6)->nullable();
            $table->integer('mov_number')->nullable();
            $table->string('pyd_description', 75)->nullable();
            $table->string('pyr_ratecode', 6)->nullable();
            $table->float('pyd_quantity', 53, 0)->nullable();
            $table->string('pyd_rateunit', 6)->nullable();
            $table->string('pyd_unit', 6)->nullable();
            $table->decimal('pyd_rate', 19, 4)->nullable();
            $table->decimal('pyd_amount', 19, 4)->nullable();
            $table->string('pyd_pretax', 1)->nullable();
            $table->string('pyd_glnum', 32)->nullable();
            $table->string('pyd_currency', 6)->nullable();
            $table->dateTime('pyd_currencydate')->nullable();
            $table->string('pyd_status', 6)->nullable();
            $table->string('pyd_refnumtype', 6)->nullable();
            $table->string('pyd_refnum', 30)->nullable();
            $table->dateTime('pyh_payperiod')->nullable();
            $table->dateTime('pyd_workperiod')->nullable();
            $table->string('lgh_startpoint', 8)->nullable();
            $table->integer('lgh_startcity')->nullable();
            $table->string('lgh_endpoint', 8)->nullable();
            $table->integer('lgh_endcity')->nullable();
            $table->decimal('ivd_payrevenue', 19, 4)->nullable();
            $table->float('pyd_revenueratio', 53, 0)->nullable();
            $table->decimal('pyd_lessrevenue', 19, 4)->nullable();
            $table->decimal('pyd_payrevenue', 19, 4)->nullable();
            $table->dateTime('pyd_transdate')->nullable();
            $table->integer('pyd_minus')->nullable();
            $table->integer('pyd_sequence')->nullable();
            $table->integer('std_number')->nullable();
            $table->string('pyd_loadstate', 6)->nullable();
            $table->integer('pyd_xrefnumber')->nullable();
            $table->integer('ord_hdrnumber')->nullable();
            $table->decimal('pyt_fee1', 19, 4)->nullable();
            $table->decimal('pyt_fee2', 19, 4)->nullable();
            $table->decimal('pyd_grossamount', 19, 4)->nullable();
            $table->string('pyd_adj_flag', 1)->nullable();
            $table->string('pyd_updatedby', 20)->nullable();
            $table->integer('psd_id')->nullable();
            $table->dateTime('pyd_transferdate')->nullable();
            $table->string('pyd_exportstatus', 6)->nullable();
            $table->string('pyd_releasedby', 20)->nullable();
            $table->string('cht_itemcode', 6)->nullable();
            $table->integer('pyd_billedweight')->nullable();
            $table->string('tar_tarriffnumber', 12)->nullable();
            $table->string('psd_batch_id', 16)->nullable();
            $table->string('pyd_updsrc', 1)->nullable();
            $table->dateTime('pyd_updatedon')->nullable();
            $table->integer('pyd_offsetpay_number')->nullable();
            $table->string('pyd_credit_pay_flag', 1)->nullable();
            $table->integer('pyd_ivh_hdrnumber')->nullable();
            $table->integer('psd_number')->nullable();
            $table->string('pyd_ref_invoice', 15)->nullable();
            $table->dateTime('pyd_ref_invoicedate')->nullable();
            $table->string('pyd_ignoreglreset', 1)->nullable();
            $table->smallInteger('pyd_PostProcSource')->nullable();
            $table->string('pyd_authcode', 30)->nullable();
            $table->string('pyd_GPTrans', 6)->nullable();
            $table->string('cac_id', 10)->nullable();
            $table->string('ccc_id', 10)->nullable();
            $table->dateTime('pyd_hourlypaydate')->nullable();
            $table->string('pyd_isdefault', 1)->nullable();
            $table->decimal('pyd_mbtaxableamount', 19, 4)->nullable();
            $table->decimal('pyd_nttaxableamount', 19, 4)->nullable();
            $table->string('pyd_maxquantity_used', 1)->nullable();
            $table->string('pyd_maxcharge_used', 1)->nullable();
            $table->integer('std_number_adj')->nullable();
            $table->string('pyd_vendortopay', 12);
            $table->string('pyd_carinvnum', 30)->nullable();
            $table->dateTime('pyd_carinvdate')->nullable();
            $table->string('pyd_vendorpay', 1)->nullable();
            $table->string('pyd_remarks', 254)->nullable();
            $table->string('pyd_perdiem_exceeded', 1)->nullable();
            $table->integer('stp_number')->nullable();
            $table->integer('stp_mfh_sequence')->nullable();
            $table->dateTime('pyd_payment_date')->nullable();
            $table->string('pyd_payment_doc_number', 13)->nullable();
            $table->string('pyd_carrierinvoice_aprv', 1)->nullable();
            $table->string('pyd_carrierinvoice_rjct', 1)->nullable();
            $table->string('pyd__aprv_rjct_comment')->nullable();
            $table->string('pyd_paid_indicator', 1)->nullable();
            $table->decimal('pyd_paid_amount', 19, 4)->nullable();
            $table->string('pyd_expresscode', 50)->nullable();
            $table->string('pyd_createdby', 20)->nullable();
            $table->dateTime('pyd_createdon')->nullable();
            $table->integer('stp_number_pacos')->nullable();
            $table->decimal('pyd_gst_amount', 19, 4)->nullable();
            $table->integer('pyd_gst_flag')->nullable();
            $table->string('pyd_mileagetable', 4)->nullable();
            $table->string('pyt_otflag', 1)->nullable();
            $table->string('bill_override', 1)->nullable();
            $table->string('not_billed_reason', 256)->nullable();
            $table->dateTime('pyd_ap_check_date')->nullable();
            $table->string('pyd_ap_check_number', 30)->nullable();
            $table->decimal('pyd_ap_check_amount', 7)->nullable();
            $table->string('pyd_ap_vendor_id', 30)->nullable();
            $table->string('pyd_ap_updated_by', 20)->nullable();
            $table->float('pyd_reg_time_qty', 53, 0)->nullable();
            $table->integer('pyd_advstdnum')->nullable();
            $table->dateTime('pyd_min_period')->nullable();
            $table->string('crd_cardnumber', 20)->nullable();
            $table->string('pyd_ap_voucher_nbr', 8)->nullable();
            $table->string('pyd_workcycle_status', 30)->nullable();
            $table->string('pyd_workcycle_description', 75)->nullable();
            $table->float('pyd_thirdparty_split_percent', 53, 0);
            $table->string('pyd_basis', 6)->nullable();
            $table->string('pyd_basisunit', 6)->nullable();
            $table->string('pyd_branch_override', 12)->nullable();
            $table->string('pyd_billtype_changereason', 6)->nullable();
            $table->string('pyd_branch', 12)->nullable();
            $table->string('pyd_delays', 6)->nullable();
            $table->integer('pyd_reg_time_pydnum')->nullable();
            $table->decimal('pyd_overlimit', 19, 4)->nullable();
            $table->decimal('pyd_totaladvanced', 19, 4)->nullable();
            $table->float('pyd_coowner_split_percent', 53, 0)->nullable();
            $table->string('pyd_coowner_split_adj', 1)->nullable();
            $table->decimal('pyd_report_quantity', 19, 4)->nullable();
            $table->decimal('pyd_report_rate', 19, 4)->nullable();
            $table->integer('pyd_tprsplit_number')->nullable();
            $table->integer('pyd_tprdiffbtw_number')->nullable();
            $table->integer('pyd_atd_id')->nullable();
            $table->integer('RecurringAdjustmentDetailId')->nullable();
            $table->integer('pyd_parent_pyd_number')->nullable();
            $table->string('pyd_orig_currency', 6)->nullable();
            $table->decimal('pyd_orig_amount', 19, 4)->nullable();
            $table->decimal('pyd_cex_rate', 19, 4)->nullable();
            $table->float('pyd_rate_factor', 53, 0)->nullable();
            $table->string('pyd_fixedRate', 1)->nullable();
            $table->string('pyd_fixedQty', 1)->nullable();
            $table->string('pyd_fixedAmount', 1)->nullable();
            $table->integer('pyd_ico_ivd_number_child')->nullable();
            $table->dateTime('std_purchase_date')->nullable();
            $table->string('std_purchase_tax_state', 6)->nullable();
            $table->integer('pyd_tax_originator_pyd_number')->nullable();
            $table->dateTime('pyd_clock_start')->nullable();
            $table->dateTime('pyd_clock_end')->nullable();
            $table->string('pyd_lghtype1', 6)->nullable();
            $table->string('pyd_RemitToVendorID', 12)->nullable();
            $table->integer('pyd_smwld_id')->nullable();
            $table->integer('pyd_pair')->nullable();
            $table->string('termCode', 8)->nullable();
            $table->boolean('pyd_reconcile')->nullable();
            $table->integer('PayScheduleId')->nullable();
            $table->boolean('ExcludeGuaranteePay')->nullable();
            $table->dateTime('INS_TIMESTAMP');
            $table->string('DW_TIMESTAMP');
        });
    }

    public function down(): void
    {
        Schema::connection('psbison')->dropIfExists('paydetail');
    }
};
