<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('psbison')->create('trailerprofile', function (Blueprint $table) {
            $table->string('trl_number', 8);
            $table->string('trl_owner', 12);
            $table->string('trl_make', 8)->nullable();
            $table->string('trl_model', 12)->nullable();
            $table->integer('trl_currenthub')->nullable();
            $table->string('trl_type1', 6)->nullable();
            $table->string('trl_type2', 6)->nullable();
            $table->string('trl_type3', 6)->nullable();
            $table->string('trl_type4', 6)->nullable();
            $table->integer('trl_year')->nullable();
            $table->dateTime('trl_startdate')->nullable();
            $table->dateTime('trl_retiredate')->nullable();
            $table->float('trl_mpg', 53, 0)->nullable();
            $table->string('trl_company', 6)->nullable();
            $table->string('trl_fleet', 6)->nullable();
            $table->string('trl_division', 6)->nullable();
            $table->string('trl_terminal', 6)->nullable();
            $table->string('cmp_id', 8)->nullable();
            $table->integer('cty_code')->nullable();
            $table->string('trl_ilt', 1)->nullable();
            $table->integer('trl_mtwgt')->nullable();
            $table->integer('trl_grosswgt')->nullable();
            $table->smallInteger('trl_axles')->nullable();
            $table->float('trl_ht', 53, 0)->nullable();
            $table->float('trl_len', 53, 0)->nullable();
            $table->float('trl_wdth', 53, 0)->nullable();
            $table->string('trl_licstate', 6)->nullable();
            $table->string('trl_licnum', 12)->nullable();
            $table->string('trl_status', 6)->nullable();
            $table->string('trl_serial', 20)->nullable();
            $table->dateTime('trl_dateacquired')->nullable();
            $table->float('trl_origcost', 53, 0)->nullable();
            $table->float('trl_opercostmile', 53, 0)->nullable();
            $table->dateTime('trl_sch_date')->nullable();
            $table->string('trl_sch_cmp_id', 8)->nullable();
            $table->integer('trl_sch_city')->nullable();
            $table->string('trl_sch_status', 6)->nullable();
            $table->dateTime('trl_avail_date')->nullable();
            $table->string('trl_avail_cmp_id', 8)->nullable();
            $table->integer('trl_avail_city')->nullable();
            $table->string('trl_fix_record', 1)->nullable();
            $table->integer('trl_last_stop')->nullable();
            $table->string('trl_misc1', 254)->nullable();
            $table->string('trl_misc2', 254)->nullable();
            $table->string('trl_misc3', 254)->nullable();
            $table->string('trl_misc4', 254)->nullable();
            $table->string('trl_id', 13);
            $table->integer('trl_cur_mileage')->nullable();
            $table->string('trl_bmp_pathname')->nullable();
            $table->string('timestamp')->nullable();
            $table->string('trl_actg_type', 1)->nullable();
            $table->string('trl_ilt_scac', 4)->nullable();
            $table->string('trl_updatedby', 256)->nullable();
            $table->dateTime('trl_updateon')->nullable();
            $table->float('trl_tareweight', 53, 0)->nullable();
            $table->float('trl_kp_to_axle1', 53, 0)->nullable();
            $table->float('trl_axle1_to_axle2', 53, 0)->nullable();
            $table->float('trl_axle2_to_axle3', 53, 0)->nullable();
            $table->float('trl_axle3_to_axle4', 53, 0)->nullable();
            $table->integer('trl_comprt1_size_wet')->nullable();
            $table->integer('trl_comprt2_size_wet')->nullable();
            $table->integer('trl_comprt3_size_wet')->nullable();
            $table->integer('trl_comprt4_size_wet')->nullable();
            $table->integer('trl_comprt5_size_wet')->nullable();
            $table->integer('trl_comprt6_size_wet')->nullable();
            $table->string('trl_comprt1_uom_wet', 6)->nullable();
            $table->string('trl_comprt2_uom_wet', 6)->nullable();
            $table->string('trl_comprt3_uom_wet', 6)->nullable();
            $table->string('trl_comprt4_uom_wet', 6)->nullable();
            $table->string('trl_comprt5_uom_wet', 6)->nullable();
            $table->string('trl_comprt6_uom_wet', 6)->nullable();
            $table->string('trl_comprt1_bulkhead', 6)->nullable();
            $table->string('trl_comprt2_bulkhead', 6)->nullable();
            $table->string('trl_comprt3_bulkhead', 6)->nullable();
            $table->string('trl_comprt4_bulkhead', 6)->nullable();
            $table->string('trl_comprt5_bulkhead', 6)->nullable();
            $table->string('trl_tareweight_uom', 6)->nullable();
            $table->string('trl_kp_to_axle1_uom', 6)->nullable();
            $table->string('trl_axle1_to_axle2_uom', 6)->nullable();
            $table->string('trl_axle2_to_axle3_uom', 6)->nullable();
            $table->string('trl_axle3_to_axle4_uom', 6)->nullable();
            $table->dateTime('trl_createdate')->nullable();
            $table->string('trl_pupid', 13)->nullable();
            $table->float('trl_axle4_to_axle5', 53, 0)->nullable();
            $table->string('trl_axle4_to_axle5_uom', 6)->nullable();
            $table->float('trl_lastaxle_to_rear', 53, 0)->nullable();
            $table->string('trl_lastaxle_to_rear_uom', 6)->nullable();
            $table->float('trl_nose_to_kp', 53, 0)->nullable();
            $table->string('trl_nose_to_kp_uom', 6)->nullable();
            $table->integer('trl_total_no_of_compartments')->nullable();
            $table->float('trl_total_trailer_size_wet', 53, 0)->nullable();
            $table->string('trl_uom_wet', 6)->nullable();
            $table->float('trl_total_trailer_size_dry', 53, 0)->nullable();
            $table->string('trl_uom_dry', 6)->nullable();
            $table->integer('trl_comprt1_size_dry')->nullable();
            $table->integer('trl_comprt2_size_dry')->nullable();
            $table->integer('trl_comprt3_size_dry')->nullable();
            $table->integer('trl_comprt4_size_dry')->nullable();
            $table->integer('trl_comprt5_size_dry')->nullable();
            $table->integer('trl_comprt6_size_dry')->nullable();
            $table->string('trl_comprt1_uom_dry', 6)->nullable();
            $table->string('trl_comprt2_uom_dry', 6)->nullable();
            $table->string('trl_comprt3_uom_dry', 6)->nullable();
            $table->string('trl_comprt4_uom_dry', 6)->nullable();
            $table->string('trl_comprt5_uom_dry', 6)->nullable();
            $table->string('trl_comprt6_uom_dry', 6)->nullable();
            $table->float('trl_bulkhead_comprt1_thick', 53, 0)->nullable();
            $table->float('trl_bulkhead_comprt2_thick', 53, 0)->nullable();
            $table->float('trl_bulkhead_comprt3_thick', 53, 0)->nullable();
            $table->float('trl_bulkhead_comprt4_thick', 53, 0)->nullable();
            $table->float('trl_bulkhead_comprt5_thick', 53, 0)->nullable();
            $table->string('trl_bulkhead_comprt1_thick_uom', 6)->nullable();
            $table->string('trl_bulkhead_comprt2_thick_uom', 6)->nullable();
            $table->string('trl_bulkhead_comprt3_thick_uom', 6)->nullable();
            $table->string('trl_bulkhead_comprt4_thick_uom', 6)->nullable();
            $table->string('trl_bulkhead_comprt5_thick_uom', 6)->nullable();
            $table->string('trl_quickentry', 1)->nullable();
            $table->string('trl_wash_status', 1)->nullable();
            $table->string('trl_manualupdate', 1)->nullable();
            $table->dateTime('trl_exp1_date')->nullable();
            $table->dateTime('trl_exp2_date')->nullable();
            $table->string('trl_last_cmd', 8)->nullable();
            $table->integer('trl_last_cmd_ord')->nullable();
            $table->dateTime('trl_last_cmd_date')->nullable();
            $table->integer('trl_palletcount')->nullable();
            $table->string('bis_laststatuschgby', 30)->nullable();
            $table->dateTime('bis_laststatusdate')->nullable();
            $table->string('trl_customer_flag', 1)->nullable();
            $table->string('trl_billto_parent', 8)->nullable();
            $table->string('trl_booked_revtype1', 6)->nullable();
            $table->string('trl_next_event', 6)->nullable();
            $table->string('trl_next_cmp_id', 8)->nullable();
            $table->integer('trl_next_city')->nullable();
            $table->string('trl_next_state', 6)->nullable();
            $table->string('trl_next_region1', 6)->nullable();
            $table->string('trl_next_region2', 6)->nullable();
            $table->string('trl_next_region3', 6)->nullable();
            $table->string('trl_next_region4', 6)->nullable();
            $table->string('trl_prior_event', 6)->nullable();
            $table->string('trl_prior_cmp_id', 8)->nullable();
            $table->integer('trl_prior_city')->nullable();
            $table->string('trl_prior_state', 6)->nullable();
            $table->string('trl_prior_region1', 6)->nullable();
            $table->string('trl_prior_region2', 6)->nullable();
            $table->string('trl_prior_region3', 6)->nullable();
            $table->string('trl_prior_region4', 6)->nullable();
            $table->integer('bison_avail_city')->nullable();
            $table->dateTime('bison_avail_date')->nullable();
            $table->string('bison_avail_status', 6)->nullable();
            $table->string('bison_avail_cmp', 8)->nullable();
            $table->string('trl_accessorylist', 254)->nullable();
            $table->integer('trl_newused');
            $table->string('trl_gp_class', 15);
            $table->string('trl_worksheet_comment1', 60)->nullable();
            $table->string('trl_worksheet_comment2', 60)->nullable();
            $table->string('trl_loading_class', 6)->nullable();
            $table->float('trl_axlgrp1_tarewgt', 53, 0)->nullable();
            $table->float('trl_axlgrp1_grosswgt', 53, 0)->nullable();
            $table->float('trl_axlgrp2_tarewgt', 53, 0)->nullable();
            $table->float('trl_axlgrp2_grosswgt', 53, 0)->nullable();
            $table->dateTime('trl_exp1_enddate')->nullable();
            $table->dateTime('trl_exp2_enddate')->nullable();
            $table->string('trl_gps_desc')->nullable();
            $table->dateTime('trl_gps_date')->nullable();
            $table->integer('trl_gps_latitude')->nullable();
            $table->integer('trl_gps_longitude')->nullable();
            $table->integer('trl_gps_odometer')->nullable();
            $table->decimal('trl_lifetimemileage', 12, 1)->nullable();
            $table->string('trl_branch', 12)->nullable();
            $table->string('trl_liccountry', 50)->nullable();
            $table->string('trl_aceid', 10)->nullable();
            $table->string('trl_aceidtype', 6)->nullable();
            $table->float('trl_height', 53, 0)->nullable();
            $table->float('trl_width', 53, 0)->nullable();
            $table->string('trl_email', 50)->nullable();
            $table->string('trl_equipmenttype', 10);
            $table->string('trl_prefix', 32)->nullable();
            $table->string('trl_prior_cmp_othertype1', 6)->nullable();
            $table->string('trl_next_cmp_othertype1', 6)->nullable();
            $table->decimal('trl_capacity_wgt', 12, 4)->nullable();
            $table->decimal('trl_capacity_ldm', 10)->nullable();
            $table->integer('rowsec_rsrv_id')->nullable();
            $table->decimal('trl_dwelltime', 9, 1)->nullable();
            $table->string('bison_last_carrier', 8)->nullable();
            $table->integer('bison_last_mov')->nullable();
            $table->string('trl_useGeofencing', 5)->nullable();
            $table->float('trl_gps_heading', 53, 0)->nullable();
            $table->integer('trl_gps_speed')->nullable();
            $table->string('trl_validitychks', 1)->nullable();
            $table->float('trl_cmpt1_temp', 53, 0)->nullable();
            $table->float('trl_cmpt2_temp', 53, 0)->nullable();
            $table->float('trl_cmpt3_temp', 53, 0)->nullable();
            $table->float('trl_cmpt4_temp', 53, 0)->nullable();
            $table->float('trl_cmpt5_temp', 53, 0)->nullable();
            $table->float('trl_cmpt1_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt2_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt3_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt4_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt5_setpoint', 53, 0)->nullable();
            $table->float('trl_dischargetemp', 53, 0)->nullable();
            $table->float('trl_ambienttemp', 53, 0)->nullable();
            $table->string('trl_alarmstate', 6)->nullable();
            $table->float('trl_cmpt1_desired_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt2_desired_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt3_desired_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt4_desired_setpoint', 53, 0)->nullable();
            $table->float('trl_cmpt5_desired_setpoint', 53, 0)->nullable();
            $table->string('trl_desired_setpoints_setby', 30)->nullable();
            $table->string('trl_reeferpower', 1)->nullable();
            $table->string('trl_mcommID', 30)->nullable();
            $table->string('trl_mcommType', 6)->nullable();
            $table->integer('trl_reeferhist1')->nullable();
            $table->integer('trl_reeferhist2')->nullable();
            $table->string('trl_ams_type', 12)->nullable();
            $table->string('trl_unassigned_reasoncode', 30)->nullable();
            $table->string('trl_unassigned_comments', 250)->nullable();
            $table->string('trl_iso_code', 8)->nullable();
            $table->integer('PayScheduleId')->nullable();
            $table->integer('trl_mobilecommaccount')->nullable();
            $table->string('trl_app_eqcodes', 256)->nullable();
            $table->string('OriginDestinationOption', 6)->nullable();
            $table->string('trl_use_rfid', 1)->nullable();
            $table->string('trl_rfid_tag', 24)->nullable();
            $table->string('trl_carrier', 8)->nullable();
            $table->string('trl_double_bulk_head', 5)->nullable();
            $table->string('trl_pump_unit', 1)->nullable();
            $table->string('iso_code', 8)->nullable();
            $table->string('trl_discharge_side', 10)->nullable();
            $table->dateTime('INS_TIMESTAMP');
        });
    }

    public function down(): void
    {
        Schema::connection('psbison')->dropIfExists('trailerprofile');
    }
};
