<?php

namespace App\Models\psbison\unused;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $cmp_id
 * @property string $cmp_name
 * @property string $cmp_address1
 * @property string $cmp_address2
 * @property int $cmp_city
 * @property string $cmp_zip
 * @property string $cmp_primaryphone
 * @property string $cmp_secondaryphone
 * @property string $cmp_faxphone
 * @property string $cmp_shipper
 * @property string $cmp_consingee
 * @property string $cmp_billto
 * @property string $cmp_othertype1
 * @property string $cmp_othertype2
 * @property string $cmp_artype
 * @property string $cmp_invoicetype
 * @property string $cmp_revtype1
 * @property string $cmp_revtype2
 * @property string $cmp_revtype3
 * @property string $cmp_revtype4
 * @property string $cmp_currency
 * @property string $cmp_active
 * @property int $cmp_opens_mo
 * @property int $cmp_closes_mo
 * @property int $cmp_creditlimit
 * @property int $cmp_creditavail
 * @property string $cmp_mileagetable
 * @property string $cmp_mastercompany
 * @property string $cmp_terms
 * @property string $cmp_defaultbillto
 * @property int $cmp_edi214
 * @property int $cmp_edi210
 * @property int $cmp_edi204
 * @property string $cmp_state
 * @property string $cmp_region1
 * @property string $cmp_region2
 * @property string $cmp_region3
 * @property string $cmp_region4
 * @property string $cmp_addnewshipper
 * @property string $cmp_opensun
 * @property string $cmp_openmon
 * @property string $cmp_opentue
 * @property string $cmp_openwed
 * @property string $cmp_openthu
 * @property string $cmp_openfri
 * @property string $cmp_opensat
 * @property string $cmp_payfrom
 * @property string $cmp_mapfile
 * @property string $cmp_contact
 * @property string $cmp_directions
 * @property mixed $timestamp
 * @property string $cty_nmstct
 * @property string $cmp_misc1
 * @property string $cmp_misc2
 * @property string $cmp_misc3
 * @property string $cmp_misc4
 * @property int $cmp_mbdays
 * @property string $cmp_lastmb
 * @property int $cmp_invcopies
 * @property string $cmp_transfertype
 * @property string $cmp_altid
 * @property string $cmp_updatedby
 * @property string $cmp_updateddate
 * @property string $cmp_defaultpriority
 * @property string $cmp_invoiceto
 * @property int $cmp_invformat
 * @property string $cmp_invprintto
 * @property string $cmp_creditavail_update
 * @property string $cmd_code
 * @property string $junknotinuse
 * @property string $cmp_agedinvflag
 * @property int $cmp_max_dunnage
 * @property int $cmp_acc_balance
 * @property string $cmp_acc_dt
 * @property int $cmp_opens_tu
 * @property int $cmp_closes_tu
 * @property int $cmp_opens_we
 * @property int $cmp_closes_we
 * @property int $cmp_opens_th
 * @property int $cmp_closes_th
 * @property int $cmp_opens_fr
 * @property int $cmp_closes_fr
 * @property int $cmp_opens_sa
 * @property int $cmp_closes_sa
 * @property int $cmp_opens_su
 * @property int $cmp_closes_su
 * @property string $cmp_subcompany
 * @property string $cmp_createdate
 * @property string $cmp_taxtable1
 * @property string $cmp_taxtable2
 * @property string $cmp_taxtable3
 * @property string $cmp_taxtable4
 * @property string $cmp_quickentry
 * @property int $cmp_slack_time
 * @property string $cmp_mailto_name
 * @property string $cmp_mailto_address1
 * @property string $cmp_mailto_address2
 * @property int $cmp_mailto_city
 * @property string $cmp_mailto_state
 * @property string $cmp_mailto_zip
 * @property string $mailto_cty_nmstct
 * @property string $cmp_mailto_crterm1
 * @property string $cmp_mailto_crterm2
 * @property string $cmp_mailto_crterm3
 * @property float $cmp_latseconds
 * @property float $cmp_longseconds
 * @property string $cmp_mbformat
 * @property string $cmp_mbgroup
 * @property int $cmp_centroidcity
 * @property string $cmp_centroidctynmstct
 * @property string $cmp_centroidzip
 * @property float $cmp_ooa_mileage
 * @property float $cmp_ooa_mileage_stops
 * @property string $cmp_mapaddress
 * @property string $cmp_primaryphoneext
 * @property string $cmp_secondaryphoneext
 * @property string $cmp_usestreetaddr
 * @property int $cmp_palletcount
 * @property string $cmp_fueltableid
 * @property string $cmp_podcontact
 * @property string $cmp_podphone
 * @property int $grp_id
 * @property string $cmp_parent
 * @property string $cmp_country
 * @property string $cmp_address3
 * @property int $cmp_slacktime_late
 * @property string $cmp_geoloc
 * @property string $cmp_geoloc_forsearch
 * @property int $cmp_min_charge
 * @property string $cmp_service_location
 * @property string $cmp_psoverride
 * @property string $bisoninv_email
 * @property int $bisoninv_faxconf
 * @property int $bisoninv_customsdoc
 * @property string $bisoninv_edibillto
 * @property string $cmp_image_routing1
 * @property string $cmp_image_routing2
 * @property string $cmp_image_routing3
 * @property string $cmp_mailtoTermsMatchFlag
 * @property string $cmp_MailtToForLinehaulFlag
 * @property int $cmp_max_weight
 * @property string $cmp_max_weightunits
 * @property string $cmp_ivformat
 * @property string $cmp_ivgroup
 * @property string $cmp_addcurrencysurcharge
 * @property string $cmp_port
 * @property int $cmp_currencysurchargebase
 * @property string $cmp_taxid
 * @property string $cmp_gp_class
 * @property string $doc_language
 * @property string $cmp_depot
 * @property string $ltsl_auto_add_pul_flag
 * @property string $ltsl_default_pickup_event
 * @property string $ltsl_default_delivery_event
 * @property int $cmp_PUPTimeAllowance
 * @property int $cmp_DRPTimeAllowance
 * @property int $bison_latlongtype
 * @property string $bison_timezone
 * @property int $cmp_latlongverifications
 * @property int $cmp_maxdetmins
 * @property string $cmp_detcontacts
 * @property string $cmp_allowdetcharges
 * @property string $cmp_maptuit_customnote
 * @property int $external_id
 * @property string $external_type
 * @property string $cmp_TrlConfiguration
 * @property string $cmp_service_location_qual
 * @property string $cmp_service_location_own
 * @property string $cmp_service_location_rating
 * @property string $cmp_reftype_unique
 * @property string $cmp_MileSearchLevel
 * @property int $cmp_det_start
 * @property string $cmp_det_apply_if_late
 * @property int $cmp_leadtime
 * @property string $cmp_railramp
 * @property int $cmp_PUPalert
 * @property int $cmp_DRPalert
 * @property string $cmp_det_apply_if_early
 * @property string $cmp_senddetalert
 * @property string $cmp_athome_location
 * @property string $cmp_thirdpartytype1
 * @property string $cmp_thirdpartytype2
 * @property string $cmp_aceidtype
 * @property string $cmp_aceid
 * @property int $cmp_TMlatseconds
 * @property int $cmp_TMlongseconds
 * @property float $cmp_TMdistancetolatlong
 * @property string $cmp_TMlatlongdate
 * @property string $cmp_dimoverride
 * @property string $cmp_overrideapplyhighestrate
 * @property string $cmp_rbd_FlatRateOption
 * @property int $cmp_MinLHAdj
 * @property string $cmp_RateBy
 * @property string $cmp_rbd_highrateoption
 * @property string $cmp_bookingterminal
 * @property string $cmp_supplier
 * @property int $cmp_ICaccessorial
 * @property float $cmp_ICaccessorialfactor
 * @property string $cmp_last_call_date
 * @property string $cmp_last_call_note
 * @property string $cmp_last_call_user
 * @property string $cmp_next_call_date
 * @property string $cmp_SchdEarliestDateOverride
 * @property string $cmp_GeoCodeRequested
 * @property int $cmp_det_increment
 * @property string $cmp_det_rounding
 * @property int $cmp_det_threshold
 * @property string $cmp_det_override
 * @property string $cmp_stop_events
 * @property int $cmp_freestops
 * @property string $cmp_stopevents_pay
 * @property int $cmp_freestops_pay
 * @property string $cmp_accountof
 * @property int $cmp_avgstopminutes
 * @property string $cmp_mailto_country
 * @property string $cmp_billto_eligible_flag
 * @property string $cmp_Payment_terms
 * @property float $cmp_blended_min_qty
 * @property int $cmp_MonObsHolFlag
 * @property int $cmp_TueObsHolFlag
 * @property int $cmp_WedObsHolFlag
 * @property int $cmp_ThuObsHolFlag
 * @property int $cmp_FriObsHolFlag
 * @property int $cmp_SatObsHolFlag
 * @property int $cmp_SunObsHolFlag
 * @property int $cmp_FromHrDateAdj
 * @property string $cmp_minchargeoption
 * @property string $cmp_acc_gvt_rpt
 * @property string $cmp_acc_id
 * @property string $cmp_BelongsTo
 * @property int $rhh_id
 * @property string $cmp_inv_toll_detail
 * @property string $cmp_refnum_gpinvxfer
 * @property string $holiday_group
 * @property string $cmp_refnum
 * @property string $cmp_statemiletype1
 * @property string $cmp_statemiletype2
 * @property string $cmp_splitbillonrefnbr
 * @property string $cmp_stp_type2
 * @property string $cmp_stp_type3
 * @property string $cmp_hiddenid
 * @property string $cmp_firm_appt_value
 * @property string $cmp_invoiceby
 * @property string $cmp_volunits
 * @property string $cmp_crmtype
 * @property string $cmp_wgtunits
 * @property string $cmp_rateallocation
 * @property string $cmp_invoiceimageflag
 * @property string $cmp_TollMethod
 * @property string $cmp_AvgFuelPriceDateOverride
 * @property string $cmp_refnum_gpdocdescxfer
 * @property int $cmp_servicedrp_rpt
 * @property int $cmp_servicepup_rpt
 * @property int $cmp_servicebillto_rpt
 * @property int $rowsec_rsrv_id
 * @property string $cmp_dedicated_bill
 * @property string $cmp_house_number
 * @property string $cmp_street_name
 * @property string $cmp_inv_controlling_cmp_id
 * @property string $cmp_inv_open_ivr_forward_number
 * @property string $cmp_inv_closed_ivr_forward_number
 * @property string $cmp_inv_numeric_id
 * @property string $cmp_CreditHoldStatus
 * @property string $cmp_CreditHoldComment
 * @property string $cmp_InvSrvReleaseOnly
 * @property string $cmp_InvSrvMode
 * @property string $cmp_ForecastBatch
 * @property string $cmp_SalesHistoryBatch
 * @property string $cmp_ForecasterLastReadingDate
 * @property string $cmp_ForecasterLastRunDate
 * @property string $cmp_TaxGroup
 * @property string $cmp_UseDips
 * @property string $cmp_sourcing_include_trans
 * @property string $cmp_sourcing_include_taxes
 * @property int $cmp_sourcing_max_distance
 * @property string $cmp_sourcing_quote_type
 * @property string $cmp_sourcing_quotebillto
 * @property string $cmp_sourcing_quotetransbillto
 * @property int $cmp_ivr_pin
 * @property string $cmp_defaultstptype1
 * @property string $cmp_dedicated_usedate
 * @property string $cmp_dedicated_datecycle
 * @property string $cmp_timezone
 * @property string $cmp_othertype3
 * @property string $cmp_othertype4
 * @property string $cmp_billing_rating_engine
 * @property string $cmp_pophubmilesflag
 * @property string $cmp_custequipprefix
 * @property string $cmp_misc5
 * @property string $cmp_misc6
 * @property string $cmp_misc7
 * @property string $cmp_misc8
 * @property string $cmp_billto_spotquote
 * @property int $cmp_allow_tm_update
 * @property string $AppianDistanceFldData
 * @property string $cmp_isbond
 * @property string $cmp_invoice_when
 * @property string $cmp_doublesdrop_location
 * @property string $cmp_primaryflagrequired
 * @property string $cmp_yard_type
 * @property string $cmp_btm_toll_mileagetable
 * @property string $cmp_terminal
 * @property string $cmp_autobill
 * @property string $cmp_autobill_terms
 * @property string $cmp_useboldates
 * @property string $cmp_sendarrivalalert
 * @property string $cmp_senddeparturealert
 * @property int $cmp_cmdvalue
 * @property string $cmp_mb_breaktype
 * @property int $cmp_mb_breakvalue
 * @property string $cmp_ar_transfer_nonbundled
 * @property string $cmp_defaultcons
 * @property string $cmp_mbdayofmonth
 * @property string $cmp_RateEachPickDrop
 * @property string $cmp_inv_audit
 * @property string $cmp_app_eqcodes
 * @property string $cmp_etawcbillto
 * @property int $trl_freedays
 * @property int $trl_maxcharge
 * @property int $cmp_DRBack
 * @property int $cmp_DROut
 * @property string $cmp_dbh_custinvnum_prefix
 * @property int $cmp_dbh_custinvnum_startnum
 * @property int $cmp_dbh_custinvnum_digits
 * @property string $cmp_ar_account
 * @property string $cmp_ispreferred
 * @property string $cmp_ImagingHandlingRebill
 * @property string $cmp_ImagingHandlingMisc
 * @property float $cmp_ctw_conv
 * @property float $cmp_ctw_break
 * @property float $cmp_wtc_conv
 * @property string $cmp_ctw_weightunits
 * @property string $cmp_ctw_volumeunits
 * @property string $INS_TIMESTAMP
 */
class Company extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'Company';

    protected $fillable = ['cmp_id', 'cmp_name', 'cmp_address1', 'cmp_address2', 'cmp_city', 'cmp_zip', 'cmp_primaryphone', 'cmp_secondaryphone', 'cmp_faxphone', 'cmp_shipper', 'cmp_consingee', 'cmp_billto', 'cmp_othertype1', 'cmp_othertype2', 'cmp_artype', 'cmp_invoicetype', 'cmp_revtype1', 'cmp_revtype2', 'cmp_revtype3', 'cmp_revtype4', 'cmp_currency', 'cmp_active', 'cmp_opens_mo', 'cmp_closes_mo', 'cmp_creditlimit', 'cmp_creditavail', 'cmp_mileagetable', 'cmp_mastercompany', 'cmp_terms', 'cmp_defaultbillto', 'cmp_edi214', 'cmp_edi210', 'cmp_edi204', 'cmp_state', 'cmp_region1', 'cmp_region2', 'cmp_region3', 'cmp_region4', 'cmp_addnewshipper', 'cmp_opensun', 'cmp_openmon', 'cmp_opentue', 'cmp_openwed', 'cmp_openthu', 'cmp_openfri', 'cmp_opensat', 'cmp_payfrom', 'cmp_mapfile', 'cmp_contact', 'cmp_directions', 'timestamp', 'cty_nmstct', 'cmp_misc1', 'cmp_misc2', 'cmp_misc3', 'cmp_misc4', 'cmp_mbdays', 'cmp_lastmb', 'cmp_invcopies', 'cmp_transfertype', 'cmp_altid', 'cmp_updatedby', 'cmp_updateddate', 'cmp_defaultpriority', 'cmp_invoiceto', 'cmp_invformat', 'cmp_invprintto', 'cmp_creditavail_update', 'cmd_code', 'junknotinuse', 'cmp_agedinvflag', 'cmp_max_dunnage', 'cmp_acc_balance', 'cmp_acc_dt', 'cmp_opens_tu', 'cmp_closes_tu', 'cmp_opens_we', 'cmp_closes_we', 'cmp_opens_th', 'cmp_closes_th', 'cmp_opens_fr', 'cmp_closes_fr', 'cmp_opens_sa', 'cmp_closes_sa', 'cmp_opens_su', 'cmp_closes_su', 'cmp_subcompany', 'cmp_createdate', 'cmp_taxtable1', 'cmp_taxtable2', 'cmp_taxtable3', 'cmp_taxtable4', 'cmp_quickentry', 'cmp_slack_time', 'cmp_mailto_name', 'cmp_mailto_address1', 'cmp_mailto_address2', 'cmp_mailto_city', 'cmp_mailto_state', 'cmp_mailto_zip', 'mailto_cty_nmstct', 'cmp_mailto_crterm1', 'cmp_mailto_crterm2', 'cmp_mailto_crterm3', 'cmp_latseconds', 'cmp_longseconds', 'cmp_mbformat', 'cmp_mbgroup', 'cmp_centroidcity', 'cmp_centroidctynmstct', 'cmp_centroidzip', 'cmp_ooa_mileage', 'cmp_ooa_mileage_stops', 'cmp_mapaddress', 'cmp_primaryphoneext', 'cmp_secondaryphoneext', 'cmp_usestreetaddr', 'cmp_palletcount', 'cmp_fueltableid', 'cmp_podcontact', 'cmp_podphone', 'grp_id', 'cmp_parent', 'cmp_country', 'cmp_address3', 'cmp_slacktime_late', 'cmp_geoloc', 'cmp_geoloc_forsearch', 'cmp_min_charge', 'cmp_service_location', 'cmp_psoverride', 'bisoninv_email', 'bisoninv_faxconf', 'bisoninv_customsdoc', 'bisoninv_edibillto', 'cmp_image_routing1', 'cmp_image_routing2', 'cmp_image_routing3', 'cmp_mailtoTermsMatchFlag', 'cmp_MailtToForLinehaulFlag', 'cmp_max_weight', 'cmp_max_weightunits', 'cmp_ivformat', 'cmp_ivgroup', 'cmp_addcurrencysurcharge', 'cmp_port', 'cmp_currencysurchargebase', 'cmp_taxid', 'cmp_gp_class', 'doc_language', 'cmp_depot', 'ltsl_auto_add_pul_flag', 'ltsl_default_pickup_event', 'ltsl_default_delivery_event', 'cmp_PUPTimeAllowance', 'cmp_DRPTimeAllowance', 'bison_latlongtype', 'bison_timezone', 'cmp_latlongverifications', 'cmp_maxdetmins', 'cmp_detcontacts', 'cmp_allowdetcharges', 'cmp_maptuit_customnote', 'external_id', 'external_type', 'cmp_TrlConfiguration', 'cmp_service_location_qual', 'cmp_service_location_own', 'cmp_service_location_rating', 'cmp_reftype_unique', 'cmp_MileSearchLevel', 'cmp_det_start', 'cmp_det_apply_if_late', 'cmp_leadtime', 'cmp_railramp', 'cmp_PUPalert', 'cmp_DRPalert', 'cmp_det_apply_if_early', 'cmp_senddetalert', 'cmp_athome_location', 'cmp_thirdpartytype1', 'cmp_thirdpartytype2', 'cmp_aceidtype', 'cmp_aceid', 'cmp_TMlatseconds', 'cmp_TMlongseconds', 'cmp_TMdistancetolatlong', 'cmp_TMlatlongdate', 'cmp_dimoverride', 'cmp_overrideapplyhighestrate', 'cmp_rbd_FlatRateOption', 'cmp_MinLHAdj', 'cmp_RateBy', 'cmp_rbd_highrateoption', 'cmp_bookingterminal', 'cmp_supplier', 'cmp_ICaccessorial', 'cmp_ICaccessorialfactor', 'cmp_last_call_date', 'cmp_last_call_note', 'cmp_last_call_user', 'cmp_next_call_date', 'cmp_SchdEarliestDateOverride', 'cmp_GeoCodeRequested', 'cmp_det_increment', 'cmp_det_rounding', 'cmp_det_threshold', 'cmp_det_override', 'cmp_stop_events', 'cmp_freestops', 'cmp_stopevents_pay', 'cmp_freestops_pay', 'cmp_accountof', 'cmp_avgstopminutes', 'cmp_mailto_country', 'cmp_billto_eligible_flag', 'cmp_Payment_terms', 'cmp_blended_min_qty', 'cmp_MonObsHolFlag', 'cmp_TueObsHolFlag', 'cmp_WedObsHolFlag', 'cmp_ThuObsHolFlag', 'cmp_FriObsHolFlag', 'cmp_SatObsHolFlag', 'cmp_SunObsHolFlag', 'cmp_FromHrDateAdj', 'cmp_minchargeoption', 'cmp_acc_gvt_rpt', 'cmp_acc_id', 'cmp_BelongsTo', 'rhh_id', 'cmp_inv_toll_detail', 'cmp_refnum_gpinvxfer', 'holiday_group', 'cmp_refnum', 'cmp_statemiletype1', 'cmp_statemiletype2', 'cmp_splitbillonrefnbr', 'cmp_stp_type2', 'cmp_stp_type3', 'cmp_hiddenid', 'cmp_firm_appt_value', 'cmp_invoiceby', 'cmp_volunits', 'cmp_crmtype', 'cmp_wgtunits', 'cmp_rateallocation', 'cmp_invoiceimageflag', 'cmp_TollMethod', 'cmp_AvgFuelPriceDateOverride', 'cmp_refnum_gpdocdescxfer', 'cmp_servicedrp_rpt', 'cmp_servicepup_rpt', 'cmp_servicebillto_rpt', 'rowsec_rsrv_id', 'cmp_dedicated_bill', 'cmp_house_number', 'cmp_street_name', 'cmp_inv_controlling_cmp_id', 'cmp_inv_open_ivr_forward_number', 'cmp_inv_closed_ivr_forward_number', 'cmp_inv_numeric_id', 'cmp_CreditHoldStatus', 'cmp_CreditHoldComment', 'cmp_InvSrvReleaseOnly', 'cmp_InvSrvMode', 'cmp_ForecastBatch', 'cmp_SalesHistoryBatch', 'cmp_ForecasterLastReadingDate', 'cmp_ForecasterLastRunDate', 'cmp_TaxGroup', 'cmp_UseDips', 'cmp_sourcing_include_trans', 'cmp_sourcing_include_taxes', 'cmp_sourcing_max_distance', 'cmp_sourcing_quote_type', 'cmp_sourcing_quotebillto', 'cmp_sourcing_quotetransbillto', 'cmp_ivr_pin', 'cmp_defaultstptype1', 'cmp_dedicated_usedate', 'cmp_dedicated_datecycle', 'cmp_timezone', 'cmp_othertype3', 'cmp_othertype4', 'cmp_billing_rating_engine', 'cmp_pophubmilesflag', 'cmp_custequipprefix', 'cmp_misc5', 'cmp_misc6', 'cmp_misc7', 'cmp_misc8', 'cmp_billto_spotquote', 'cmp_allow_tm_update', 'AppianDistanceFldData', 'cmp_isbond', 'cmp_invoice_when', 'cmp_doublesdrop_location', 'cmp_primaryflagrequired', 'cmp_yard_type', 'cmp_btm_toll_mileagetable', 'cmp_terminal', 'cmp_autobill', 'cmp_autobill_terms', 'cmp_useboldates', 'cmp_sendarrivalalert', 'cmp_senddeparturealert', 'cmp_cmdvalue', 'cmp_mb_breaktype', 'cmp_mb_breakvalue', 'cmp_ar_transfer_nonbundled', 'cmp_defaultcons', 'cmp_mbdayofmonth', 'cmp_RateEachPickDrop', 'cmp_inv_audit', 'cmp_app_eqcodes', 'cmp_etawcbillto', 'trl_freedays', 'trl_maxcharge', 'cmp_DRBack', 'cmp_DROut', 'cmp_dbh_custinvnum_prefix', 'cmp_dbh_custinvnum_startnum', 'cmp_dbh_custinvnum_digits', 'cmp_ar_account', 'cmp_ispreferred', 'cmp_ImagingHandlingRebill', 'cmp_ImagingHandlingMisc', 'cmp_ctw_conv', 'cmp_ctw_break', 'cmp_wtc_conv', 'cmp_ctw_weightunits', 'cmp_ctw_volumeunits', 'INS_TIMESTAMP'];

    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'psbison';
}
