<?php

namespace App\Models\psbison\unused;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $ord_company
 * @property string $ord_number
 * @property string $ord_customer
 * @property string $ord_bookdate
 * @property string $ord_bookedby
 * @property string $ord_status
 * @property string $ord_originpoint
 * @property string $ord_destpoint
 * @property string $ord_invoicestatus
 * @property int $ord_origincity
 * @property int $ord_destcity
 * @property string $ord_originstate
 * @property string $ord_deststate
 * @property string $ord_originregion1
 * @property string $ord_destregion1
 * @property string $ord_supplier
 * @property string $ord_billto
 * @property string $ord_startdate
 * @property string $ord_completiondate
 * @property string $ord_revtype1
 * @property string $ord_revtype2
 * @property string $ord_revtype3
 * @property string $ord_revtype4
 * @property float $ord_totalweight
 * @property float $ord_totalpieces
 * @property int $ord_totalmiles
 * @property float $ord_totalcharge
 * @property string $ord_currency
 * @property string $ord_currencydate
 * @property float $ord_totalvolume
 * @property int $ord_hdrnumber
 * @property string $ord_refnum
 * @property string $ord_invoicewhole
 * @property string $ord_remark
 * @property string $ord_shipper
 * @property string $ord_consignee
 * @property string $ord_pu_at
 * @property string $ord_dr_at
 * @property string $ord_originregion2
 * @property string $ord_originregion3
 * @property string $ord_originregion4
 * @property string $ord_destregion2
 * @property string $ord_destregion3
 * @property string $ord_destregion4
 * @property int $mfh_hdrnumber
 * @property string $ord_priority
 * @property int $mov_number
 * @property string $tar_tarriffnumber
 * @property int $tar_number
 * @property mixed $timestamp
 * @property string $tar_tariffitem
 * @property string $ord_contact
 * @property string $ord_showshipper
 * @property string $ord_showcons
 * @property string $ord_subcompany
 * @property int $ord_lowtemp
 * @property int $ord_hitemp
 * @property float $ord_quantity
 * @property int $ord_rate
 * @property int $ord_charge
 * @property string $ord_rateunit
 * @property string $ord_unit
 * @property string $trl_type1
 * @property string $ord_driver1
 * @property string $ord_driver2
 * @property string $ord_tractor
 * @property string $ord_trailer
 * @property int $ord_length
 * @property int $ord_width
 * @property int $ord_height
 * @property string $ord_lengthunit
 * @property string $ord_widthunit
 * @property string $ord_heightunit
 * @property string $ord_reftype
 * @property string $cmd_code
 * @property string $ord_description
 * @property string $ord_terms
 * @property string $cht_itemcode
 * @property string $ord_origin_earliestdate
 * @property string $ord_origin_latestdate
 * @property int $ord_odmetermiles
 * @property int $ord_stopcount
 * @property string $ord_dest_earliestdate
 * @property string $ord_dest_latestdate
 * @property string $ref_sid
 * @property string $ref_pickup
 * @property int $ord_cmdvalue
 * @property int $ord_accessorial_chrg
 * @property string $ord_availabledate
 * @property float $ord_miscqty
 * @property string $ord_tempunits
 * @property string $ord_datetaken
 * @property string $ord_totalweightunits
 * @property string $ord_totalvolumeunits
 * @property string $ord_totalcountunits
 * @property float $ord_loadtime
 * @property float $ord_unloadtime
 * @property float $ord_drivetime
 * @property string $ord_rateby
 * @property int $ord_quantity_type
 * @property string $ord_thirdpartytype1
 * @property string $ord_thirdpartytype2
 * @property int $ord_notified
 * @property int $ord_ldmiles
 * @property int $ord_mtmiles
 * @property int $ord_invalidmiles
 * @property int $ord_charge_type
 * @property string $ord_bol_printed
 * @property string $ord_fromorder
 * @property int $ord_mintemp
 * @property int $ord_maxtemp
 * @property string $ord_distributor
 * @property int $ord_carriermiles
 * @property string $opt_trc_type4
 * @property string $opt_trl_type4
 * @property int $ord_cod_amount
 * @property string $appt_init
 * @property string $appt_contact
 * @property float $ord_ratingquantity
 * @property string $ord_ratingunit
 * @property string $bis_insertedby
 * @property int $bis_lumperamt
 * @property string $bis_lumperdate
 * @property string $ord_hideshipperaddr
 * @property string $ord_hideconsignaddr
 * @property string $ord_booked_revtype1
 * @property string $ord_mileagetable
 * @property int $ord_tareweight
 * @property int $ord_grossweight
 * @property string $ord_trl_type2
 * @property string $ord_trl_type3
 * @property string $ord_trl_type4
 * @property int $ord_allinclusivecharge
 * @property string $ord_extrainfo1
 * @property string $ord_extrainfo2
 * @property string $ord_extrainfo3
 * @property string $ord_extrainfo4
 * @property string $ord_extrainfo5
 * @property string $ord_extrainfo6
 * @property string $ord_extrainfo7
 * @property string $ord_extrainfo8
 * @property string $ord_extrainfo9
 * @property string $ord_extrainfo10
 * @property string $ord_extrainfo11
 * @property string $ord_extrainfo12
 * @property string $ord_extrainfo13
 * @property string $ord_extrainfo14
 * @property string $ord_extrainfo15
 * @property int $ord_rate_type
 * @property string $ord_barcode
 * @property string $ord_broker
 * @property float $ord_stlquantity
 * @property string $ord_stlunit
 * @property int $ord_stlquantity_type
 * @property int $ord_fromschedule
 * @property int $ord_schedulebatch
 * @property string $bis_trailer
 * @property string $last_updateby
 * @property string $last_updatedate
 * @property float $ord_mileage_adj_pct
 * @property string $ord_intermodal
 * @property int $Ord_UnlockKey
 * @property string $ord_trlrentinv
 * @property int $ord_revenue_pay_fix
 * @property int $ord_revenue_pay
 * @property string $ord_reserved_number
 * @property int $ord_customs_document
 * @property int $ord_charge_type_lh
 * @property int $ord_noautosplit
 * @property int $ord_noautotransfer
 * @property string $ord_complete_stamp
 * @property float $ord_totalloadingmeters
 * @property string $ord_totalloadingmetersunit
 * @property string $ord_entryport
 * @property string $ord_exitport
 * @property float $ord_commodities_weight
 * @property string $ord_order_source
 * @property int $external_id
 * @property string $external_type
 * @property float $ord_dimfactor
 * @property string $ord_TrlConfiguration
 * @property string $ord_origin_zip
 * @property string $ord_dest_zip
 * @property int $ord_toll_cost
 * @property string $ord_toll_cost_update_date
 * @property string $ord_raildest
 * @property string $ord_railpoolid
 * @property string $ord_trailer2
 * @property string $ord_rate_mileagetable
 * @property int $ord_odmetermiles_mtid
 * @property string $ord_route
 * @property string $ord_route_effc_date
 * @property string $ord_route_exp_date
 * @property string $ord_edipurpose
 * @property string $ord_ediuseraction
 * @property int $ord_edistate
 * @property string $ord_no_recalc_miles
 * @property string $ord_editradingpartner
 * @property string $ord_edideclinereason
 * @property string $ord_carrier
 * @property string $ord_miscdate1
 * @property string $ord_pyd_status_1
 * @property string $ord_pyd_status_2
 * @property string $ord_pin
 * @property string $ord_accounttype
 * @property string $ord_shortcomment
 * @property string $ord_lastratedate
 * @property int $ord_manualeventcallminutes
 * @property int $ord_manualcheckcallminutes
 * @property string $ord_batchrateeligibility
 * @property string $ord_batchratestatus
 * @property int $ord_odometer_start
 * @property int $ord_odometer_end
 * @property int $ord_billmiles
 * @property int $ord_paymiles
 * @property int $ord_standardhours
 * @property string $ord_preventexternalupdate
 * @property int $ord_job_ordered
 * @property int $ord_job_remaining
 * @property string $sv_manu_export_flag
 * @property string $ord_cbp
 * @property string $ord_cyclic_dsp_enabled
 * @property string $ord_preassign_ack_required
 * @property string $ord_anc_number
 * @property string $ord_gvw_unit
 * @property float $ord_gvw_amt
 * @property string $ord_gvw_adjstd_unit
 * @property float $ord_gvw_adjstd_amt
 * @property string $ord_BelongsTo
 * @property string $ord_chassis
 * @property string $ord_chassis2
 * @property int $ord_showasconsignee_dist
 * @property string $ord_use_showasconsignee_dist
 * @property string $ord_nomincharges
 * @property int $car_key
 * @property string $GST_REQ
 * @property string $QST_REQ
 * @property string $ord_thirdpartytype3
 * @property float $ord_thirdparty_split_percent
 * @property string $ord_thirdparty_split
 * @property string $ord_carrierchangecode
 * @property string $ord_extequip_automatch
 * @property string $IVA_REQ
 * @property float $ord_broker_percent
 * @property float $ord_target_margin
 * @property string $ord_paystatus_override
 * @property string $ord_customdate
 * @property int $ord_edistate_prior
 * @property string $ord_railramporig
 * @property string $ord_railrampdest
 * @property int $rowsec_rsrv_id
 * @property string $ord_reviewneeded
 * @property string $ord_DelRptSent
 * @property string $recurring_job_flag
 * @property string $ord_reviewed
 * @property string $ord_reviewedby
 * @property string $ord_revieweddate
 * @property int $ord_tpmiles
 * @property int $ord_intermodalmiles
 * @property string $ord_remark2
 * @property string $ord_timezone
 * @property string $ord_routename
 * @property string $ord_datepromised
 * @property string $ord_billing_usedate
 * @property string $ord_billing_usedate_setting
 * @property string $ord_pallet_type
 * @property int $ord_pallet_count
 * @property string $payrollcloseddate
 * @property string $billingcloseddate
 * @property string $ord_override_stop_type
 * @property string $ord_invoice_effectivedate
 * @property string $ord_checklisttype
 * @property string $ord_mastermatchpending
 * @property string $ord_railschedulecascadepending
 * @property string $ord_importexport
 * @property string $ord_pendinglegstatusupdate
 * @property string $ord_submode
 * @property bool $ord_job_freightbased
 * @property string $ord_approved
 * @property string $HST_REQ
 * @property string $ord_ratemode
 * @property string $ord_servicelevel
 * @property int $ord_servicedays
 * @property string $ord_over_credit_limit_approved
 * @property string $ord_over_credit_limit_approved_by
 * @property string $ord_triprpt_last_rundate
 * @property string $ord_app_eqcodes
 * @property string $ord_totalmileunits
 * @property float $ord_totalpallets
 * @property string $ord_totalpalletunits
 * @property float $ord_totalcount2
 * @property string $ord_totalcount2units
 * @property float $ord_rate_per
 * @property float $ord_sub_charge
 * @property float $ord_discount_rate
 * @property float $ord_discount
 * @property float $ord_discount_qty
 * @property float $ord_discount_per
 * @property int $ord_disc_tar_number
 * @property string $INS_TIMESTAMP
 */
class OrderHeader extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'OrderHeader';

    protected $fillable = ['ord_company', 'ord_number', 'ord_customer', 'ord_bookdate', 'ord_bookedby', 'ord_status', 'ord_originpoint', 'ord_destpoint', 'ord_invoicestatus', 'ord_origincity', 'ord_destcity', 'ord_originstate', 'ord_deststate', 'ord_originregion1', 'ord_destregion1', 'ord_supplier', 'ord_billto', 'ord_startdate', 'ord_completiondate', 'ord_revtype1', 'ord_revtype2', 'ord_revtype3', 'ord_revtype4', 'ord_totalweight', 'ord_totalpieces', 'ord_totalmiles', 'ord_totalcharge', 'ord_currency', 'ord_currencydate', 'ord_totalvolume', 'ord_hdrnumber', 'ord_refnum', 'ord_invoicewhole', 'ord_remark', 'ord_shipper', 'ord_consignee', 'ord_pu_at', 'ord_dr_at', 'ord_originregion2', 'ord_originregion3', 'ord_originregion4', 'ord_destregion2', 'ord_destregion3', 'ord_destregion4', 'mfh_hdrnumber', 'ord_priority', 'mov_number', 'tar_tarriffnumber', 'tar_number', 'timestamp', 'tar_tariffitem', 'ord_contact', 'ord_showshipper', 'ord_showcons', 'ord_subcompany', 'ord_lowtemp', 'ord_hitemp', 'ord_quantity', 'ord_rate', 'ord_charge', 'ord_rateunit', 'ord_unit', 'trl_type1', 'ord_driver1', 'ord_driver2', 'ord_tractor', 'ord_trailer', 'ord_length', 'ord_width', 'ord_height', 'ord_lengthunit', 'ord_widthunit', 'ord_heightunit', 'ord_reftype', 'cmd_code', 'ord_description', 'ord_terms', 'cht_itemcode', 'ord_origin_earliestdate', 'ord_origin_latestdate', 'ord_odmetermiles', 'ord_stopcount', 'ord_dest_earliestdate', 'ord_dest_latestdate', 'ref_sid', 'ref_pickup', 'ord_cmdvalue', 'ord_accessorial_chrg', 'ord_availabledate', 'ord_miscqty', 'ord_tempunits', 'ord_datetaken', 'ord_totalweightunits', 'ord_totalvolumeunits', 'ord_totalcountunits', 'ord_loadtime', 'ord_unloadtime', 'ord_drivetime', 'ord_rateby', 'ord_quantity_type', 'ord_thirdpartytype1', 'ord_thirdpartytype2', 'ord_notified', 'ord_ldmiles', 'ord_mtmiles', 'ord_invalidmiles', 'ord_charge_type', 'ord_bol_printed', 'ord_fromorder', 'ord_mintemp', 'ord_maxtemp', 'ord_distributor', 'ord_carriermiles', 'opt_trc_type4', 'opt_trl_type4', 'ord_cod_amount', 'appt_init', 'appt_contact', 'ord_ratingquantity', 'ord_ratingunit', 'bis_insertedby', 'bis_lumperamt', 'bis_lumperdate', 'ord_hideshipperaddr', 'ord_hideconsignaddr', 'ord_booked_revtype1', 'ord_mileagetable', 'ord_tareweight', 'ord_grossweight', 'ord_trl_type2', 'ord_trl_type3', 'ord_trl_type4', 'ord_allinclusivecharge', 'ord_extrainfo1', 'ord_extrainfo2', 'ord_extrainfo3', 'ord_extrainfo4', 'ord_extrainfo5', 'ord_extrainfo6', 'ord_extrainfo7', 'ord_extrainfo8', 'ord_extrainfo9', 'ord_extrainfo10', 'ord_extrainfo11', 'ord_extrainfo12', 'ord_extrainfo13', 'ord_extrainfo14', 'ord_extrainfo15', 'ord_rate_type', 'ord_barcode', 'ord_broker', 'ord_stlquantity', 'ord_stlunit', 'ord_stlquantity_type', 'ord_fromschedule', 'ord_schedulebatch', 'bis_trailer', 'last_updateby', 'last_updatedate', 'ord_mileage_adj_pct', 'ord_intermodal', 'Ord_UnlockKey', 'ord_trlrentinv', 'ord_revenue_pay_fix', 'ord_revenue_pay', 'ord_reserved_number', 'ord_customs_document', 'ord_charge_type_lh', 'ord_noautosplit', 'ord_noautotransfer', 'ord_complete_stamp', 'ord_totalloadingmeters', 'ord_totalloadingmetersunit', 'ord_entryport', 'ord_exitport', 'ord_commodities_weight', 'ord_order_source', 'external_id', 'external_type', 'ord_dimfactor', 'ord_TrlConfiguration', 'ord_origin_zip', 'ord_dest_zip', 'ord_toll_cost', 'ord_toll_cost_update_date', 'ord_raildest', 'ord_railpoolid', 'ord_trailer2', 'ord_rate_mileagetable', 'ord_odmetermiles_mtid', 'ord_route', 'ord_route_effc_date', 'ord_route_exp_date', 'ord_edipurpose', 'ord_ediuseraction', 'ord_edistate', 'ord_no_recalc_miles', 'ord_editradingpartner', 'ord_edideclinereason', 'ord_carrier', 'ord_miscdate1', 'ord_pyd_status_1', 'ord_pyd_status_2', 'ord_pin', 'ord_accounttype', 'ord_shortcomment', 'ord_lastratedate', 'ord_manualeventcallminutes', 'ord_manualcheckcallminutes', 'ord_batchrateeligibility', 'ord_batchratestatus', 'ord_odometer_start', 'ord_odometer_end', 'ord_billmiles', 'ord_paymiles', 'ord_standardhours', 'ord_preventexternalupdate', 'ord_job_ordered', 'ord_job_remaining', 'sv_manu_export_flag', 'ord_cbp', 'ord_cyclic_dsp_enabled', 'ord_preassign_ack_required', 'ord_anc_number', 'ord_gvw_unit', 'ord_gvw_amt', 'ord_gvw_adjstd_unit', 'ord_gvw_adjstd_amt', 'ord_BelongsTo', 'ord_chassis', 'ord_chassis2', 'ord_showasconsignee_dist', 'ord_use_showasconsignee_dist', 'ord_nomincharges', 'car_key', 'GST_REQ', 'QST_REQ', 'ord_thirdpartytype3', 'ord_thirdparty_split_percent', 'ord_thirdparty_split', 'ord_carrierchangecode', 'ord_extequip_automatch', 'IVA_REQ', 'ord_broker_percent', 'ord_target_margin', 'ord_paystatus_override', 'ord_customdate', 'ord_edistate_prior', 'ord_railramporig', 'ord_railrampdest', 'rowsec_rsrv_id', 'ord_reviewneeded', 'ord_DelRptSent', 'recurring_job_flag', 'ord_reviewed', 'ord_reviewedby', 'ord_revieweddate', 'ord_tpmiles', 'ord_intermodalmiles', 'ord_remark2', 'ord_timezone', 'ord_routename', 'ord_datepromised', 'ord_billing_usedate', 'ord_billing_usedate_setting', 'ord_pallet_type', 'ord_pallet_count', 'payrollcloseddate', 'billingcloseddate', 'ord_override_stop_type', 'ord_invoice_effectivedate', 'ord_checklisttype', 'ord_mastermatchpending', 'ord_railschedulecascadepending', 'ord_importexport', 'ord_pendinglegstatusupdate', 'ord_submode', 'ord_job_freightbased', 'ord_approved', 'HST_REQ', 'ord_ratemode', 'ord_servicelevel', 'ord_servicedays', 'ord_over_credit_limit_approved', 'ord_over_credit_limit_approved_by', 'ord_triprpt_last_rundate', 'ord_app_eqcodes', 'ord_totalmileunits', 'ord_totalpallets', 'ord_totalpalletunits', 'ord_totalcount2', 'ord_totalcount2units', 'ord_rate_per', 'ord_sub_charge', 'ord_discount_rate', 'ord_discount', 'ord_discount_qty', 'ord_discount_per', 'ord_disc_tar_number', 'INS_TIMESTAMP'];

    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'psbison';
}
