<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('driverservice')->create('app_application', function (Blueprint $table) {
            $table->string('NAME', 50)->nullable()->unique('pk_name');
            $table->string('CITY', 30)->nullable();
            $table->string('POSITION', 30)->nullable();
            $table->string('PARTNER', 30)->nullable();
            $table->dateTime('ADAT')->nullable();
            $table->string('TELE', 20)->nullable();
            $table->integer('TEAM')->nullable();
            $table->integer('SINGLE')->nullable();
            $table->float('EXPYRS', 53, 0)->nullable();
            $table->integer('CDN')->nullable();
            $table->integer('USA')->nullable();
            $table->integer('LONGH')->nullable();
            $table->integer('MTNS')->nullable();
            $table->integer('SHORH')->nullable();
            $table->integer('ROADT')->nullable();
            $table->integer('ICC')->nullable();
            $table->integer('REFCHK')->nullable();
            $table->integer('IVIEW')->nullable();
            $table->integer('POLICE')->nullable();
            $table->integer('ABSTRACT')->nullable();
            $table->string('STATUS', 50)->nullable();
            $table->string('SHORTREASON', 50)->nullable();
            $table->text('REASON')->nullable();
            $table->dateTime('CBKDAT')->nullable();
            $table->string('SUPV', 50)->nullable();
            $table->dateTime('PDAT')->nullable();
            $table->string('PROV', 50)->nullable();
            $table->string('POST', 10)->nullable();
            $table->string('ADD1', 50)->nullable();
            $table->string('ADD2', 50)->nullable();
            $table->string('FAX', 50)->nullable();
            $table->string('FAXMAIL', 50)->nullable();
            $table->dateTime('APPRECD')->nullable();
            $table->integer('CLASS1AZ')->nullable();
            $table->string('SOURCE', 50)->nullable();
            $table->string('SOURCEDRVR', 50)->nullable();
            $table->integer('ENTERUS')->nullable();
            $table->integer('ACCID')->nullable();
            $table->text('ACCIDM')->nullable();
            $table->string('TRIPDUR', 50)->nullable();
            $table->string('POSN', 50)->nullable();
            $table->smallInteger('TORONTO')->nullable();
            $table->dateTime('REFCOMPL')->nullable();
            $table->float('YMTNS', 53, 0)->nullable();
            $table->float('YUSA', 53, 0)->nullable();
            $table->float('YCDN', 53, 0)->nullable();
            $table->float('YTORONTO', 53, 0)->nullable();
            $table->dateTime('birthdate')->nullable();
            $table->string('sin', 12)->nullable();
            $table->integer('drvlic')->nullable();
            $table->integer('cvor')->nullable();
            $table->integer('proofcit')->nullable();
            $table->string('approveby', 20)->nullable();
            $table->dateTime('approvedate')->nullable();
            $table->string('signby', 20)->nullable();
            $table->dateTime('signdate')->nullable();
            $table->string('interviewby', 20)->nullable();
            $table->dateTime('interviewdate')->nullable();
            $table->dateTime('roadtestdate')->nullable();
            $table->dateTime('drugtestdate')->nullable();
            $table->string('milesoption', 20)->nullable();
            $table->text('conditions')->nullable();
            $table->dateTime('orientdate')->nullable();
            $table->integer('preemploy')->nullable();
            $table->integer('smoker')->nullable();
            $table->string('hotelpo', 20)->nullable();
            $table->dateTime('hotelfrom')->nullable();
            $table->dateTime('hotelto')->nullable();
            $table->dateTime('checkcalldate')->nullable();
            $table->string('fleet', 20)->nullable();
            $table->string('drivercode', 20)->nullable();
            $table->string('oounit', 20)->nullable();
            $table->string('ridein', 30)->nullable();
            $table->integer('reimburse')->nullable();
            $table->integer('datasheet')->nullable();
            $table->dateTime('rdtestsignoffdate')->nullable();
            $table->string('rdtestsignoffby', 20)->nullable();
            $table->string('rideinordnum', 20)->nullable();
            $table->text('interviewnotes')->nullable();
            $table->integer('arrangements')->nullable();
            $table->integer('CDRP')->nullable();
            $table->integer('nonsmoker')->nullable();
            $table->tinyInteger('bonus_sign_active')->nullable();
            $table->tinyInteger('bonus_refer_active')->nullable();
            $table->string('bonus_refer_who', 20)->nullable();
            $table->string('apptakenby', 20)->nullable();
            $table->tinyInteger('bonus_refer_RRSP')->nullable();
            $table->tinyInteger('bonus_refer_elig')->nullable();
            $table->string('callback_reason', 20)->nullable();
            $table->dateTime('decline_date')->nullable();
            $table->string('decline_by', 20)->nullable();
            $table->dateTime('app_sent')->nullable();
            $table->string('app_sentby', 20)->nullable();
            $table->string('app_format', 20)->nullable();
            $table->string('app_emailaddr', 80)->nullable();
            $table->string('app_status', 6)->nullable();
            $table->string('app_inqrefby', 50)->nullable();
            $table->string('app_nosentreason', 50)->nullable();
            $table->string('systemcomment', 20)->nullable();
            $table->dateTime('app_inqfollowup')->nullable();
            $table->tinyInteger('app_fastcard')->nullable();
            $table->tinyInteger('app_signedpayscale')->nullable();
            $table->tinyInteger('app_orientkit')->nullable();
            $table->tinyInteger('app_other')->nullable();
            $table->string('app_otherdesc', 50)->nullable();
            $table->integer('coe_mindays')->nullable();
            $table->string('coe_tractoryard', 50)->nullable();
            $table->decimal('coe_signonbonus', 19, 4)->nullable();
            $table->string('coe_payscaletype', 50)->nullable();
            $table->text('coe_timeoff')->nullable();
            $table->text('coe_missingdoc')->nullable();
            $table->text('coe_preference')->nullable();
            $table->text('coe_additional')->nullable();
            $table->tinyInteger('coe_nonyc')->nullable();
            $table->tinyInteger('coe_interimss')->nullable();
            $table->string('app_terminal', 20)->nullable();
            $table->string('app_division', 20)->nullable();
            $table->tinyInteger('app_waiver')->nullable();
            $table->tinyInteger('app_pardon')->nullable();
            $table->string('bonus_refer_HR', 50)->nullable();
            $table->dateTime('app_lastcommentdate')->nullable();
            $table->string('app_orientloc', 20)->nullable();
            $table->string('app_driverprogram', 20)->nullable();
            $table->tinyInteger('bonus_sign_elig')->nullable();
            $table->float('YCITY', 53, 0)->nullable();
            $table->float('YLOGGING', 53, 0)->nullable();
            $table->string('app_assignto', 50)->nullable();
            $table->text('app_assignNote')->nullable();
            $table->tinyInteger('app_safetyapproved')->nullable();
            $table->tinyInteger('app_safetydeclined')->nullable();
            $table->string('app_safetyexception', 50)->nullable();
            $table->string('app_safetyapprovedby', 50)->nullable();
            $table->text('app_safetycomments')->nullable();
            $table->dateTime('app_safetyapprovedon')->nullable();
            $table->integer('app_webID')->nullable()->index('dk_appid');
            $table->string('app_firstname')->nullable();
            $table->string('app_lastname')->nullable();
            $table->text('app_trainingREQ')->nullable();
            $table->integer('app_hubspotID')->nullable()->index('dk_hubspot');
            $table->increments('ID');
        });
    }

    public function down(): void
    {
        Schema::connection('driverservice')->dropIfExists('app_application');
    }
};
