<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('driverservice')->create('acc_accident', function (Blueprint $table) {
            $table->integer('acc_id')->nullable()->index('pk_accid');
            $table->string('mpp_id', 8)->nullable()->index('dk_mppid');
            $table->string('mpp_fleet', 8)->nullable();
            $table->string('mpp_last', 50)->nullable();
            $table->string('mpp_first', 50)->nullable();
            $table->string('mpp_license', 50)->nullable();
            $table->string('mpp_province', 2)->nullable();
            $table->dateTime('mpp_birthday')->nullable();
            $table->string('mpp_restrictions', 50)->nullable();
            $table->string('mpp_phone', 20)->nullable();
            $table->string('mpp_type', 10)->nullable();
            $table->smallInteger('acc_fault')->nullable();
            $table->string('acc_prevent', 8)->nullable();
            $table->integer('acc_incident')->nullable();
            $table->integer('acc_reportable')->nullable();
            $table->integer('acc_hazmat')->nullable();
            $table->integer('acc_safedriver')->nullable();
            $table->dateTime('acc_opendate')->nullable();
            $table->dateTime('acc_date')->nullable();
            $table->dateTime('acc_closedate')->nullable();
            $table->integer('acc_thirdparty')->nullable();
            $table->decimal('acc_tpamount', 19, 4)->nullable();
            $table->string('acc_tpname', 50)->nullable();
            $table->string('acc_mpiclaim', 50)->nullable();
            $table->string('acc_mpicargoclaim', 50)->nullable();
            $table->dateTime('acc_mpiinv')->nullable();
            $table->decimal('acc_mpiamount', 19, 4)->nullable();
            $table->dateTime('acc_tpinv')->nullable();
            $table->decimal('acc_downamount', 19, 4)->nullable();
            $table->string('acc_location', 50)->nullable();
            $table->string('acc_city', 50)->nullable();
            $table->string('acc_province', 50)->nullable();
            $table->string('acc_accidentphone', 50)->nullable();
            $table->string('acc_policereport', 50)->nullable();
            $table->string('acc_officer', 50)->nullable();
            $table->string('acc_officephone', 50)->nullable();
            $table->string('acc_officerdetahcment', 50)->nullable();
            $table->string('acc_cruiser', 50)->nullable();
            $table->string('acc_drvcitation', 50)->nullable();
            $table->string('acc_othercitation', 50)->nullable();
            $table->string('acc_drvoffense', 50)->nullable();
            $table->string('acc_otheroffense', 50)->nullable();
            $table->float('acc_drvhours', 53, 0)->nullable();
            $table->integer('acc_daysoutsince48')->nullable();
            $table->float('acc_hrsleft8', 53, 0)->nullable();
            $table->string('acc_triporigin', 50)->nullable();
            $table->string('acc_tripdestination', 50)->nullable();
            $table->text('acc_description')->nullable();
            $table->text('acc_propertydamage')->nullable();
            $table->float('acc_yearsexp', 53, 0)->nullable();
            $table->float('acc_lengthemp', 53, 0)->nullable();
            $table->string('acc_locationphone', 30)->nullable();
            $table->smallInteger('vio_code')->nullable();
            $table->tinyInteger('acc_uscitation')->nullable();
            $table->tinyInteger('acc_ustowed')->nullable();
            $table->tinyInteger('acc_usfatal')->nullable();
            $table->tinyInteger('acc_usinjuries')->nullable();
            $table->decimal('acc_oocoststrc', 19, 4)->nullable();
            $table->decimal('acc_oocoststrl', 19, 4)->nullable();
            $table->decimal('acc_oocostscargo', 19, 4)->nullable();
            $table->decimal('acc_oocoststp', 19, 4)->nullable();
            $table->integer('acc_policereportorder')->nullable();
            $table->integer('acc_propdmgrecov')->nullable();
            $table->integer('acc_pointsassessed')->nullable();
            $table->integer('acc_interview')->nullable();
            $table->string('acc_status', 10)->nullable();
            $table->string('acc_progress', 10)->nullable();
            $table->string('acc_recovparty', 50)->nullable();
            $table->string('acc_invoice1', 20)->nullable();
            $table->string('acc_invoice2', 20)->nullable();
            $table->string('acc_roadcond', 20)->nullable();
            $table->string('acc_weathercond', 20)->nullable();
            $table->float('acc_expenseamt', 53, 0)->nullable();
            $table->float('acc_physicaldamage', 53, 0)->nullable();
            $table->float('acc_bodilyinjury', 53, 0)->nullable();
            $table->tinyInteger('acc_trainreq')->nullable();
            $table->tinyInteger('acc_traincomp')->nullable();
            $table->tinyInteger('acc_oodrvtobededuct')->nullable();
            $table->tinyInteger('acc_oodrvdeduct')->nullable();
            $table->tinyInteger('acc_oodrvreimb')->nullable();
            $table->tinyInteger('acc_oodrvcomp')->nullable();
            $table->tinyInteger('wtg_drvreport')->nullable();
            $table->tinyInteger('wtg_est')->nullable();
            $table->tinyInteger('wtg_trk_repairs')->nullable();
            $table->tinyInteger('wtg_trl_repairs')->nullable();
            $table->tinyInteger('wtg_bisoninv')->nullable();
            $table->tinyInteger('wtg_payment')->nullable();
            $table->tinyInteger('wtg_acct')->nullable();
            $table->tinyInteger('wtg_mpi')->nullable();
            $table->tinyInteger('wtg_tpinv')->nullable();
            $table->tinyInteger('wtg_release')->nullable();
            $table->dateTime('acc_lastupdate')->nullable();
            $table->tinyInteger('acc_isaccident')->nullable();
            $table->tinyInteger('acc_iscargo')->nullable();
            $table->dateTime('acc_enterdate')->nullable();
            $table->string('acc_liability', 10)->nullable();
            $table->string('acc_region', 10)->nullable();
            $table->string('acc_cause', 10)->nullable();
            $table->string('acc_lastupdateby', 30)->nullable();
            $table->integer('clm_id')->nullable();
            $table->string('old_prevent', 10)->nullable();
            $table->tinyInteger('sdrp_reset')->nullable();
            $table->decimal('sdrp_newrate', 19, 4)->nullable();
            $table->integer('sdrp_acctype')->nullable();
            $table->string('mpp_division', 8)->nullable();
            $table->integer('sdrp_resetdrv')->nullable();
            $table->integer('acc_reportableTP')->nullable();
            $table->float('acc_SafetyScore', 53, 0)->nullable();
            $table->tinyInteger('acc_noInjuries')->nullable();
            $table->tinyInteger('acc_bisonPersonal')->nullable();
            $table->string('acc_quantitySpilled', 20)->nullable();
            $table->string('acc_whoCalledEnv', 20)->nullable();
            $table->tinyInteger('acc_tpCheckbox')->nullable();
            $table->tinyInteger('acc_treatedAtScene')->nullable();
            $table->tinyInteger('acc_ambulance')->nullable();
            $table->tinyInteger('acc_ambulanceOnScene')->nullable();
            $table->tinyInteger('acc_areaSecuredYes')->nullable();
            $table->tinyInteger('acc_areaSecuredNo')->nullable();
            $table->string('acc_securedHow', 20)->nullable();
            $table->tinyInteger('acc_towContacted')->nullable();
            $table->tinyInteger('acc_byPolice')->nullable();
            $table->tinyInteger('acc_byShop')->nullable();
            $table->tinyInteger('acc_fuelSpill')->nullable();
            $table->tinyInteger('acc_hazmatSpill')->nullable();
            $table->tinyInteger('acc_spillContained')->nullable();
            $table->string('acc_hazmatClass', 50)->nullable();
            $table->tinyInteger('acc_directorOfSafety')->nullable();
            $table->tinyInteger('acc_environmental')->nullable();
            $table->tinyInteger('acc_ministry')->nullable();
            $table->tinyInteger('acc_policeOnScene')->nullable();
            $table->tinyInteger('acc_policeContact')->nullable();
            $table->tinyInteger('acc_fireOnScene')->nullable();
            $table->tinyInteger('acc_fireContacted')->nullable();
            $table->tinyInteger('acc_witnessInfo')->nullable();
            $table->tinyInteger('acc_picturesYes')->nullable();
            $table->tinyInteger('acc_picturesNo')->nullable();
            $table->tinyInteger('acc_bisonAndTP')->nullable();
            $table->tinyInteger('acc_skidmarks')->nullable();
            $table->tinyInteger('acc_tpLicensePlate')->nullable();
            $table->tinyInteger('acc_roadway')->nullable();
            $table->tinyInteger('acc_other')->nullable();
            $table->string('acc_speedTravelling', 8)->nullable();
            $table->tinyInteger('acc_cruise')->nullable();
            $table->string('acc_postedSpeed', 8)->nullable();
            $table->tinyInteger('acc_visibleSkidMarks')->nullable();
            $table->string('acc_distanceBrakesApplied', 20)->nullable();
            $table->string('acc_numberLanes', 20)->nullable();
            $table->string('acc_direction', 20)->nullable();
            $table->string('acc_lane', 20)->nullable();
            $table->string('acc_traffic', 20)->nullable();
            $table->tinyInteger('acc_sunYes')->nullable();
            $table->tinyInteger('acc_sunNo')->nullable();
            $table->string('acc_controlDevices', 20)->nullable();
            $table->tinyInteger('acc_tracUpright')->nullable();
            $table->tinyInteger('acc_tracDS')->nullable();
            $table->tinyInteger('acc_tracPS')->nullable();
            $table->tinyInteger('acc_tracBlocking')->nullable();
            $table->tinyInteger('acc_tracinDitch')->nullable();
            $table->tinyInteger('acc_propertyDamageYes')->nullable();
            $table->tinyInteger('acc_propertyDamageNo')->nullable();
            $table->tinyInteger('acc_trailerContentsYes')->nullable();
            $table->tinyInteger('acc_trailerContentsNo')->nullable();
            $table->string('acc_trailerContentsExplain', 50)->nullable();
            $table->string('acc_driverRescuedLocation', 20)->nullable();
            $table->tinyInteger('acc_drugAlcoholYes')->nullable();
            $table->tinyInteger('acc_drugAlcoholNo')->nullable();
            $table->tinyInteger('acc_driverRescuedYes')->nullable();
            $table->tinyInteger('acc_driverRescuedNo')->nullable();
            $table->tinyInteger('acc_operateBisonYes')->nullable();
            $table->tinyInteger('acc_operateBisonNo')->nullable();
            $table->tinyInteger('acc_groundedYes')->nullable();
            $table->tinyInteger('acc_groundedNo')->nullable();
            $table->tinyInteger('acc_consumedrugYes')->nullable();
            $table->tinyInteger('acc_consumedrugNo')->nullable();
            $table->string('acc_consumedrugExplain', 50)->nullable();
            $table->tinyInteger('acc_medRestrictionYes')->nullable();
            $table->tinyInteger('acc_medRestrictionNo')->nullable();
            $table->string('acc_medRestrictionExplain', 50)->nullable();
            $table->tinyInteger('acc_correctiveLensesYes')->nullable();
            $table->tinyInteger('acc_correctiveLensesNo')->nullable();
            $table->tinyInteger('acc_wearingLensesYes')->nullable();
            $table->tinyInteger('acc_wearingLensesNo')->nullable();
            $table->tinyInteger('acc_trlUpright')->nullable();
            $table->tinyInteger('acc_trlDS')->nullable();
            $table->tinyInteger('acc_trlPS')->nullable();
            $table->tinyInteger('acc_trlBlocking')->nullable();
            $table->tinyInteger('acc_trlinDitch')->nullable();
            $table->string('acc_propertyDamageExplain', 50)->nullable();
            $table->string('car_id', 8)->nullable();
            $table->smallInteger('acc_carrierfault')->nullable();
        });
    }

    public function down(): void
    {
        Schema::connection('driverservice')->dropIfExists('acc_accident');
    }
};
