<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('driverservice')->create('DriverSurvey', function (Blueprint $table) {
            $table->increments('RecordID');
            $table->integer('TotalYears')->nullable();
            $table->string('Region', 10)->nullable();
            $table->string('DrivingPosition', 50)->nullable();
            $table->string('Name', 50)->nullable();
            $table->string('FleetNumber', 10)->nullable();
            $table->text('Sec11a')->nullable();
            $table->integer('Sec11b')->nullable();
            $table->integer('Sec11c')->nullable();
            $table->integer('Sec11d')->nullable();
            $table->integer('Sec11e')->nullable();
            $table->integer('Sec11f')->nullable();
            $table->integer('Sec11g')->nullable();
            $table->integer('Sec12a')->nullable();
            $table->integer('Sec12b')->nullable();
            $table->text('Sec13')->nullable();
            $table->text('Sec21')->nullable();
            $table->text('Sec22')->nullable();
            $table->text('Sec23a')->nullable();
            $table->integer('Sec23b')->nullable();
            $table->integer('Sec23c')->nullable();
            $table->integer('Sec23d')->nullable();
            $table->integer('Sec23f')->nullable();
            $table->integer('Sec23g')->nullable();
            $table->integer('Sec23h')->nullable();
            $table->integer('Sec23i')->nullable();
            $table->integer('Sec23j')->nullable();
            $table->text('Sec23k')->nullable();
            $table->text('Sec24a')->nullable();
            $table->integer('Sec24b')->nullable();
            $table->integer('Sec24c')->nullable();
            $table->integer('Sec24d')->nullable();
            $table->integer('Sec24e')->nullable();
            $table->integer('Sec24f')->nullable();
            $table->integer('Sec24g')->nullable();
            $table->integer('Sec24h')->nullable();
            $table->text('Sec24i')->nullable();
            $table->integer('Sec25a')->nullable();
            $table->text('Sec25b')->nullable();
            $table->integer('Sec25c')->nullable();
            $table->text('Sec25d')->nullable();
            $table->integer('Sec25e')->nullable();
            $table->text('Sec25f')->nullable();
            $table->integer('Sec25g')->nullable();
            $table->text('Sec25h')->nullable();
            $table->integer('Sec25iday')->nullable();
            $table->integer('Sec25iweek')->nullable();
            $table->integer('Sec25imonth')->nullable();
            $table->integer('Sec25k')->nullable();
            $table->text('Sec25l')->nullable();
            $table->text('Sec25lwhy')->nullable();
            $table->integer('Sec25m')->nullable();
            $table->integer('Sec26')->nullable();
            $table->integer('Sec27')->nullable();
            $table->text('Sec28')->nullable();
            $table->integer('Sec31')->nullable();
            $table->integer('Sec32a')->nullable();
            $table->integer('Sec32b')->nullable();
            $table->integer('Sec32c')->nullable();
            $table->integer('Sec32d')->nullable();
            $table->integer('Sec32e')->nullable();
            $table->integer('Sec33a')->nullable();
            $table->integer('Sec33b')->nullable();
            $table->integer('Sec33c')->nullable();
            $table->integer('Sec33d')->nullable();
            $table->integer('Sec33e')->nullable();
            $table->integer('Sec33f')->nullable();
            $table->integer('Sec33g')->nullable();
            $table->integer('Sec33h')->nullable();
            $table->integer('Sec34a')->nullable();
            $table->integer('Sec34b')->nullable();
            $table->integer('Sec34c')->nullable();
            $table->integer('Sec34d')->nullable();
            $table->integer('Sec34e')->nullable();
            $table->integer('Sec34f')->nullable();
            $table->integer('Sec34g')->nullable();
            $table->integer('Sec34h')->nullable();
            $table->integer('Sec35a')->nullable();
            $table->text('Sec35ai')->nullable();
            $table->integer('Sec35b')->nullable();
            $table->text('Sec35bi')->nullable();
            $table->integer('Sec35c')->nullable();
            $table->text('Sec35ci')->nullable();
            $table->integer('Sec35d')->nullable();
            $table->text('Sec35di')->nullable();
            $table->integer('Sec35e')->nullable();
            $table->text('Sec35ei')->nullable();
            $table->integer('Sec35f')->nullable();
            $table->text('Sec35fi')->nullable();
            $table->integer('Sec35g')->nullable();
            $table->text('Sec35gi')->nullable();
            $table->integer('Sec35h')->nullable();
            $table->text('Sec35hi')->nullable();
            $table->integer('Sec35i')->nullable();
            $table->text('Sec35ii')->nullable();
            $table->integer('Sec35j')->nullable();
            $table->text('Sec35ji')->nullable();
            $table->integer('Sec35k')->nullable();
            $table->text('Sec35ki')->nullable();
            $table->integer('Sec35l')->nullable();
            $table->text('Sec35li')->nullable();
            $table->integer('Sec41a')->nullable();
            $table->text('Sec41ai')->nullable();
            $table->integer('Sec41b')->nullable();
            $table->text('Sec41bi')->nullable();
            $table->integer('Sec41c')->nullable();
            $table->text('Sec41ci')->nullable();
            $table->integer('Sec41d')->nullable();
            $table->text('Sec41di')->nullable();
            $table->integer('Sec41e')->nullable();
            $table->text('Sec41ei')->nullable();
            $table->integer('Sec41f')->nullable();
            $table->text('Sec41fi')->nullable();
            $table->integer('Sec41g')->nullable();
            $table->text('Sec41gi')->nullable();
            $table->integer('Sec41h')->nullable();
            $table->text('Sec41hi')->nullable();
            $table->integer('Sec41i')->nullable();
            $table->text('Sec41ii')->nullable();
            $table->integer('Sec41j')->nullable();
            $table->text('Sec41ji')->nullable();
            $table->integer('Sec41k')->nullable();
            $table->text('Sec41ki')->nullable();
            $table->string('Sec42a', 10)->nullable();
            $table->string('Sec42b', 10)->nullable();
            $table->text('Sec42c')->nullable();
            $table->text('Sec42d')->nullable();
            $table->string('DriverType', 25)->nullable();
            $table->integer('Sec23e')->nullable();
            $table->integer('YearsWithBison')->nullable();
            $table->text('Sec25mwhy')->nullable();
            $table->text('Sec25jweek')->nullable();
            $table->text('Sec25jday')->nullable();
            $table->text('Sec25jMonth')->nullable();
        });
    }

    public function down(): void
    {
        Schema::connection('driverservice')->dropIfExists('DriverSurvey');
    }
};
